# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/gero/Documents/Taller/TP3/TP_final-2025c2-Grupo20

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/gero/Documents/Taller/TP3/TP_final-2025c2-Grupo20

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/gero/Documents/Taller/TP3/TP_final-2025c2-Grupo20/CMakeFiles /home/gero/Documents/Taller/TP3/TP_final-2025c2-Grupo20//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/gero/Documents/Taller/TP3/TP_final-2025c2-Grupo20/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named taller_common

# Build rule for target.
taller_common: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 taller_common
.PHONY : taller_common

# fast build rule for target.
taller_common/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_common.dir/build.make CMakeFiles/taller_common.dir/build
.PHONY : taller_common/fast

#=============================================================================
# Target rules for targets named taller_client

# Build rule for target.
taller_client: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 taller_client
.PHONY : taller_client

# fast build rule for target.
taller_client/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_client.dir/build.make CMakeFiles/taller_client.dir/build
.PHONY : taller_client/fast

#=============================================================================
# Target rules for targets named taller_client_autogen_timestamp_deps

# Build rule for target.
taller_client_autogen_timestamp_deps: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 taller_client_autogen_timestamp_deps
.PHONY : taller_client_autogen_timestamp_deps

# fast build rule for target.
taller_client_autogen_timestamp_deps/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_client_autogen_timestamp_deps.dir/build.make CMakeFiles/taller_client_autogen_timestamp_deps.dir/build
.PHONY : taller_client_autogen_timestamp_deps/fast

#=============================================================================
# Target rules for targets named taller_client_autogen

# Build rule for target.
taller_client_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 taller_client_autogen
.PHONY : taller_client_autogen

# fast build rule for target.
taller_client_autogen/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_client_autogen.dir/build.make CMakeFiles/taller_client_autogen.dir/build
.PHONY : taller_client_autogen/fast

#=============================================================================
# Target rules for targets named sdl_headers_copy

# Build rule for target.
sdl_headers_copy: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sdl_headers_copy
.PHONY : sdl_headers_copy

# fast build rule for target.
sdl_headers_copy/fast:
	$(MAKE) $(MAKESILENT) -f _deps/sdl2-build/CMakeFiles/sdl_headers_copy.dir/build.make _deps/sdl2-build/CMakeFiles/sdl_headers_copy.dir/build
.PHONY : sdl_headers_copy/fast

#=============================================================================
# Target rules for targets named SDL2main

# Build rule for target.
SDL2main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 SDL2main
.PHONY : SDL2main

# fast build rule for target.
SDL2main/fast:
	$(MAKE) $(MAKESILENT) -f _deps/sdl2-build/CMakeFiles/SDL2main.dir/build.make _deps/sdl2-build/CMakeFiles/SDL2main.dir/build
.PHONY : SDL2main/fast

#=============================================================================
# Target rules for targets named SDL2

# Build rule for target.
SDL2: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 SDL2
.PHONY : SDL2

# fast build rule for target.
SDL2/fast:
	$(MAKE) $(MAKESILENT) -f _deps/sdl2-build/CMakeFiles/SDL2.dir/build.make _deps/sdl2-build/CMakeFiles/SDL2.dir/build
.PHONY : SDL2/fast

#=============================================================================
# Target rules for targets named SDL2-static

# Build rule for target.
SDL2-static: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 SDL2-static
.PHONY : SDL2-static

# fast build rule for target.
SDL2-static/fast:
	$(MAKE) $(MAKESILENT) -f _deps/sdl2-build/CMakeFiles/SDL2-static.dir/build.make _deps/sdl2-build/CMakeFiles/SDL2-static.dir/build
.PHONY : SDL2-static/fast

#=============================================================================
# Target rules for targets named SDL2_test

# Build rule for target.
SDL2_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 SDL2_test
.PHONY : SDL2_test

# fast build rule for target.
SDL2_test/fast:
	$(MAKE) $(MAKESILENT) -f _deps/sdl2-build/CMakeFiles/SDL2_test.dir/build.make _deps/sdl2-build/CMakeFiles/SDL2_test.dir/build
.PHONY : SDL2_test/fast

#=============================================================================
# Target rules for targets named uninstall

# Build rule for target.
uninstall: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 uninstall
.PHONY : uninstall

# fast build rule for target.
uninstall/fast:
	$(MAKE) $(MAKESILENT) -f _deps/sdl2-build/CMakeFiles/uninstall.dir/build.make _deps/sdl2-build/CMakeFiles/uninstall.dir/build
.PHONY : uninstall/fast

#=============================================================================
# Target rules for targets named SDL2_image

# Build rule for target.
SDL2_image: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 SDL2_image
.PHONY : SDL2_image

# fast build rule for target.
SDL2_image/fast:
	$(MAKE) $(MAKESILENT) -f _deps/sdl2_image-build/CMakeFiles/SDL2_image.dir/build.make _deps/sdl2_image-build/CMakeFiles/SDL2_image.dir/build
.PHONY : SDL2_image/fast

#=============================================================================
# Target rules for targets named SDL2_mixer

# Build rule for target.
SDL2_mixer: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 SDL2_mixer
.PHONY : SDL2_mixer

# fast build rule for target.
SDL2_mixer/fast:
	$(MAKE) $(MAKESILENT) -f _deps/sdl2_mixer-build/CMakeFiles/SDL2_mixer.dir/build.make _deps/sdl2_mixer-build/CMakeFiles/SDL2_mixer.dir/build
.PHONY : SDL2_mixer/fast

#=============================================================================
# Target rules for targets named SDL2_ttf

# Build rule for target.
SDL2_ttf: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 SDL2_ttf
.PHONY : SDL2_ttf

# fast build rule for target.
SDL2_ttf/fast:
	$(MAKE) $(MAKESILENT) -f _deps/sdl2_ttf-build/CMakeFiles/SDL2_ttf.dir/build.make _deps/sdl2_ttf-build/CMakeFiles/SDL2_ttf.dir/build
.PHONY : SDL2_ttf/fast

#=============================================================================
# Target rules for targets named SDL2pp

# Build rule for target.
SDL2pp: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 SDL2pp
.PHONY : SDL2pp

# fast build rule for target.
SDL2pp/fast:
	$(MAKE) $(MAKESILENT) -f _deps/libsdl2pp-build/CMakeFiles/SDL2pp.dir/build.make _deps/libsdl2pp-build/CMakeFiles/SDL2pp.dir/build
.PHONY : SDL2pp/fast

client/Pantallas/carselectscreen.o: client/Pantallas/carselectscreen.cpp.o
.PHONY : client/Pantallas/carselectscreen.o

# target to build an object file
client/Pantallas/carselectscreen.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_client.dir/build.make CMakeFiles/taller_client.dir/client/Pantallas/carselectscreen.cpp.o
.PHONY : client/Pantallas/carselectscreen.cpp.o

client/Pantallas/carselectscreen.i: client/Pantallas/carselectscreen.cpp.i
.PHONY : client/Pantallas/carselectscreen.i

# target to preprocess a source file
client/Pantallas/carselectscreen.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_client.dir/build.make CMakeFiles/taller_client.dir/client/Pantallas/carselectscreen.cpp.i
.PHONY : client/Pantallas/carselectscreen.cpp.i

client/Pantallas/carselectscreen.s: client/Pantallas/carselectscreen.cpp.s
.PHONY : client/Pantallas/carselectscreen.s

# target to generate assembly for a file
client/Pantallas/carselectscreen.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_client.dir/build.make CMakeFiles/taller_client.dir/client/Pantallas/carselectscreen.cpp.s
.PHONY : client/Pantallas/carselectscreen.cpp.s

client/Pantallas/lobbyscreen.o: client/Pantallas/lobbyscreen.cpp.o
.PHONY : client/Pantallas/lobbyscreen.o

# target to build an object file
client/Pantallas/lobbyscreen.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_client.dir/build.make CMakeFiles/taller_client.dir/client/Pantallas/lobbyscreen.cpp.o
.PHONY : client/Pantallas/lobbyscreen.cpp.o

client/Pantallas/lobbyscreen.i: client/Pantallas/lobbyscreen.cpp.i
.PHONY : client/Pantallas/lobbyscreen.i

# target to preprocess a source file
client/Pantallas/lobbyscreen.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_client.dir/build.make CMakeFiles/taller_client.dir/client/Pantallas/lobbyscreen.cpp.i
.PHONY : client/Pantallas/lobbyscreen.cpp.i

client/Pantallas/lobbyscreen.s: client/Pantallas/lobbyscreen.cpp.s
.PHONY : client/Pantallas/lobbyscreen.s

# target to generate assembly for a file
client/Pantallas/lobbyscreen.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_client.dir/build.make CMakeFiles/taller_client.dir/client/Pantallas/lobbyscreen.cpp.s
.PHONY : client/Pantallas/lobbyscreen.cpp.s

client/Pantallas/loginscreen.o: client/Pantallas/loginscreen.cpp.o
.PHONY : client/Pantallas/loginscreen.o

# target to build an object file
client/Pantallas/loginscreen.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_client.dir/build.make CMakeFiles/taller_client.dir/client/Pantallas/loginscreen.cpp.o
.PHONY : client/Pantallas/loginscreen.cpp.o

client/Pantallas/loginscreen.i: client/Pantallas/loginscreen.cpp.i
.PHONY : client/Pantallas/loginscreen.i

# target to preprocess a source file
client/Pantallas/loginscreen.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_client.dir/build.make CMakeFiles/taller_client.dir/client/Pantallas/loginscreen.cpp.i
.PHONY : client/Pantallas/loginscreen.cpp.i

client/Pantallas/loginscreen.s: client/Pantallas/loginscreen.cpp.s
.PHONY : client/Pantallas/loginscreen.s

# target to generate assembly for a file
client/Pantallas/loginscreen.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_client.dir/build.make CMakeFiles/taller_client.dir/client/Pantallas/loginscreen.cpp.s
.PHONY : client/Pantallas/loginscreen.cpp.s

client/client.o: client/client.cpp.o
.PHONY : client/client.o

# target to build an object file
client/client.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_client.dir/build.make CMakeFiles/taller_client.dir/client/client.cpp.o
.PHONY : client/client.cpp.o

client/client.i: client/client.cpp.i
.PHONY : client/client.i

# target to preprocess a source file
client/client.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_client.dir/build.make CMakeFiles/taller_client.dir/client/client.cpp.i
.PHONY : client/client.cpp.i

client/client.s: client/client.cpp.s
.PHONY : client/client.s

# target to generate assembly for a file
client/client.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_client.dir/build.make CMakeFiles/taller_client.dir/client/client.cpp.s
.PHONY : client/client.cpp.s

client/client_main.o: client/client_main.cpp.o
.PHONY : client/client_main.o

# target to build an object file
client/client_main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_client.dir/build.make CMakeFiles/taller_client.dir/client/client_main.cpp.o
.PHONY : client/client_main.cpp.o

client/client_main.i: client/client_main.cpp.i
.PHONY : client/client_main.i

# target to preprocess a source file
client/client_main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_client.dir/build.make CMakeFiles/taller_client.dir/client/client_main.cpp.i
.PHONY : client/client_main.cpp.i

client/client_main.s: client/client_main.cpp.s
.PHONY : client/client_main.s

# target to generate assembly for a file
client/client_main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_client.dir/build.make CMakeFiles/taller_client.dir/client/client_main.cpp.s
.PHONY : client/client_main.cpp.s

client/client_protocol.o: client/client_protocol.cpp.o
.PHONY : client/client_protocol.o

# target to build an object file
client/client_protocol.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_client.dir/build.make CMakeFiles/taller_client.dir/client/client_protocol.cpp.o
.PHONY : client/client_protocol.cpp.o

client/client_protocol.i: client/client_protocol.cpp.i
.PHONY : client/client_protocol.i

# target to preprocess a source file
client/client_protocol.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_client.dir/build.make CMakeFiles/taller_client.dir/client/client_protocol.cpp.i
.PHONY : client/client_protocol.cpp.i

client/client_protocol.s: client/client_protocol.cpp.s
.PHONY : client/client_protocol.s

# target to generate assembly for a file
client/client_protocol.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_client.dir/build.make CMakeFiles/taller_client.dir/client/client_protocol.cpp.s
.PHONY : client/client_protocol.cpp.s

client/mainwindow.o: client/mainwindow.cpp.o
.PHONY : client/mainwindow.o

# target to build an object file
client/mainwindow.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_client.dir/build.make CMakeFiles/taller_client.dir/client/mainwindow.cpp.o
.PHONY : client/mainwindow.cpp.o

client/mainwindow.i: client/mainwindow.cpp.i
.PHONY : client/mainwindow.i

# target to preprocess a source file
client/mainwindow.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_client.dir/build.make CMakeFiles/taller_client.dir/client/mainwindow.cpp.i
.PHONY : client/mainwindow.cpp.i

client/mainwindow.s: client/mainwindow.cpp.s
.PHONY : client/mainwindow.s

# target to generate assembly for a file
client/mainwindow.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_client.dir/build.make CMakeFiles/taller_client.dir/client/mainwindow.cpp.s
.PHONY : client/mainwindow.cpp.s

client/receiver.o: client/receiver.cpp.o
.PHONY : client/receiver.o

# target to build an object file
client/receiver.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_client.dir/build.make CMakeFiles/taller_client.dir/client/receiver.cpp.o
.PHONY : client/receiver.cpp.o

client/receiver.i: client/receiver.cpp.i
.PHONY : client/receiver.i

# target to preprocess a source file
client/receiver.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_client.dir/build.make CMakeFiles/taller_client.dir/client/receiver.cpp.i
.PHONY : client/receiver.cpp.i

client/receiver.s: client/receiver.cpp.s
.PHONY : client/receiver.s

# target to generate assembly for a file
client/receiver.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_client.dir/build.make CMakeFiles/taller_client.dir/client/receiver.cpp.s
.PHONY : client/receiver.cpp.s

client/sender.o: client/sender.cpp.o
.PHONY : client/sender.o

# target to build an object file
client/sender.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_client.dir/build.make CMakeFiles/taller_client.dir/client/sender.cpp.o
.PHONY : client/sender.cpp.o

client/sender.i: client/sender.cpp.i
.PHONY : client/sender.i

# target to preprocess a source file
client/sender.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_client.dir/build.make CMakeFiles/taller_client.dir/client/sender.cpp.i
.PHONY : client/sender.cpp.i

client/sender.s: client/sender.cpp.s
.PHONY : client/sender.s

# target to generate assembly for a file
client/sender.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_client.dir/build.make CMakeFiles/taller_client.dir/client/sender.cpp.s
.PHONY : client/sender.cpp.s

common/liberror.o: common/liberror.cpp.o
.PHONY : common/liberror.o

# target to build an object file
common/liberror.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_common.dir/build.make CMakeFiles/taller_common.dir/common/liberror.cpp.o
.PHONY : common/liberror.cpp.o

common/liberror.i: common/liberror.cpp.i
.PHONY : common/liberror.i

# target to preprocess a source file
common/liberror.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_common.dir/build.make CMakeFiles/taller_common.dir/common/liberror.cpp.i
.PHONY : common/liberror.cpp.i

common/liberror.s: common/liberror.cpp.s
.PHONY : common/liberror.s

# target to generate assembly for a file
common/liberror.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_common.dir/build.make CMakeFiles/taller_common.dir/common/liberror.cpp.s
.PHONY : common/liberror.cpp.s

common/resolver.o: common/resolver.cpp.o
.PHONY : common/resolver.o

# target to build an object file
common/resolver.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_common.dir/build.make CMakeFiles/taller_common.dir/common/resolver.cpp.o
.PHONY : common/resolver.cpp.o

common/resolver.i: common/resolver.cpp.i
.PHONY : common/resolver.i

# target to preprocess a source file
common/resolver.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_common.dir/build.make CMakeFiles/taller_common.dir/common/resolver.cpp.i
.PHONY : common/resolver.cpp.i

common/resolver.s: common/resolver.cpp.s
.PHONY : common/resolver.s

# target to generate assembly for a file
common/resolver.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_common.dir/build.make CMakeFiles/taller_common.dir/common/resolver.cpp.s
.PHONY : common/resolver.cpp.s

common/resolvererror.o: common/resolvererror.cpp.o
.PHONY : common/resolvererror.o

# target to build an object file
common/resolvererror.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_common.dir/build.make CMakeFiles/taller_common.dir/common/resolvererror.cpp.o
.PHONY : common/resolvererror.cpp.o

common/resolvererror.i: common/resolvererror.cpp.i
.PHONY : common/resolvererror.i

# target to preprocess a source file
common/resolvererror.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_common.dir/build.make CMakeFiles/taller_common.dir/common/resolvererror.cpp.i
.PHONY : common/resolvererror.cpp.i

common/resolvererror.s: common/resolvererror.cpp.s
.PHONY : common/resolvererror.s

# target to generate assembly for a file
common/resolvererror.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_common.dir/build.make CMakeFiles/taller_common.dir/common/resolvererror.cpp.s
.PHONY : common/resolvererror.cpp.s

common/socket.o: common/socket.cpp.o
.PHONY : common/socket.o

# target to build an object file
common/socket.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_common.dir/build.make CMakeFiles/taller_common.dir/common/socket.cpp.o
.PHONY : common/socket.cpp.o

common/socket.i: common/socket.cpp.i
.PHONY : common/socket.i

# target to preprocess a source file
common/socket.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_common.dir/build.make CMakeFiles/taller_common.dir/common/socket.cpp.i
.PHONY : common/socket.cpp.i

common/socket.s: common/socket.cpp.s
.PHONY : common/socket.s

# target to generate assembly for a file
common/socket.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_common.dir/build.make CMakeFiles/taller_common.dir/common/socket.cpp.s
.PHONY : common/socket.cpp.s

taller_client_autogen/mocs_compilation.o: taller_client_autogen/mocs_compilation.cpp.o
.PHONY : taller_client_autogen/mocs_compilation.o

# target to build an object file
taller_client_autogen/mocs_compilation.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_client.dir/build.make CMakeFiles/taller_client.dir/taller_client_autogen/mocs_compilation.cpp.o
.PHONY : taller_client_autogen/mocs_compilation.cpp.o

taller_client_autogen/mocs_compilation.i: taller_client_autogen/mocs_compilation.cpp.i
.PHONY : taller_client_autogen/mocs_compilation.i

# target to preprocess a source file
taller_client_autogen/mocs_compilation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_client.dir/build.make CMakeFiles/taller_client.dir/taller_client_autogen/mocs_compilation.cpp.i
.PHONY : taller_client_autogen/mocs_compilation.cpp.i

taller_client_autogen/mocs_compilation.s: taller_client_autogen/mocs_compilation.cpp.s
.PHONY : taller_client_autogen/mocs_compilation.s

# target to generate assembly for a file
taller_client_autogen/mocs_compilation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_client.dir/build.make CMakeFiles/taller_client.dir/taller_client_autogen/mocs_compilation.cpp.s
.PHONY : taller_client_autogen/mocs_compilation.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... sdl_headers_copy"
	@echo "... taller_client_autogen"
	@echo "... taller_client_autogen_timestamp_deps"
	@echo "... uninstall"
	@echo "... SDL2"
	@echo "... SDL2-static"
	@echo "... SDL2_image"
	@echo "... SDL2_mixer"
	@echo "... SDL2_test"
	@echo "... SDL2_ttf"
	@echo "... SDL2main"
	@echo "... SDL2pp"
	@echo "... taller_client"
	@echo "... taller_common"
	@echo "... client/Pantallas/carselectscreen.o"
	@echo "... client/Pantallas/carselectscreen.i"
	@echo "... client/Pantallas/carselectscreen.s"
	@echo "... client/Pantallas/lobbyscreen.o"
	@echo "... client/Pantallas/lobbyscreen.i"
	@echo "... client/Pantallas/lobbyscreen.s"
	@echo "... client/Pantallas/loginscreen.o"
	@echo "... client/Pantallas/loginscreen.i"
	@echo "... client/Pantallas/loginscreen.s"
	@echo "... client/client.o"
	@echo "... client/client.i"
	@echo "... client/client.s"
	@echo "... client/client_main.o"
	@echo "... client/client_main.i"
	@echo "... client/client_main.s"
	@echo "... client/client_protocol.o"
	@echo "... client/client_protocol.i"
	@echo "... client/client_protocol.s"
	@echo "... client/mainwindow.o"
	@echo "... client/mainwindow.i"
	@echo "... client/mainwindow.s"
	@echo "... client/receiver.o"
	@echo "... client/receiver.i"
	@echo "... client/receiver.s"
	@echo "... client/sender.o"
	@echo "... client/sender.i"
	@echo "... client/sender.s"
	@echo "... common/liberror.o"
	@echo "... common/liberror.i"
	@echo "... common/liberror.s"
	@echo "... common/resolver.o"
	@echo "... common/resolver.i"
	@echo "... common/resolver.s"
	@echo "... common/resolvererror.o"
	@echo "... common/resolvererror.i"
	@echo "... common/resolvererror.s"
	@echo "... common/socket.o"
	@echo "... common/socket.i"
	@echo "... common/socket.s"
	@echo "... taller_client_autogen/mocs_compilation.o"
	@echo "... taller_client_autogen/mocs_compilation.i"
	@echo "... taller_client_autogen/mocs_compilation.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

