# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/nacho/Escritorio/TALLER/TP_final-2025c2-Grupo20

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/nacho/Escritorio/TALLER/TP_final-2025c2-Grupo20

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/nacho/Escritorio/TALLER/TP_final-2025c2-Grupo20/CMakeFiles /home/nacho/Escritorio/TALLER/TP_final-2025c2-Grupo20//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/nacho/Escritorio/TALLER/TP_final-2025c2-Grupo20/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -P /home/nacho/Escritorio/TALLER/TP_final-2025c2-Grupo20/CMakeFiles/VerifyGlobs.cmake
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named taller_common

# Build rule for target.
taller_common: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 taller_common
.PHONY : taller_common

# fast build rule for target.
taller_common/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_common.dir/build.make CMakeFiles/taller_common.dir/build
.PHONY : taller_common/fast

#=============================================================================
# Target rules for targets named taller_client

# Build rule for target.
taller_client: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 taller_client
.PHONY : taller_client

# fast build rule for target.
taller_client/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_client.dir/build.make CMakeFiles/taller_client.dir/build
.PHONY : taller_client/fast

#=============================================================================
# Target rules for targets named taller_editor

# Build rule for target.
taller_editor: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 taller_editor
.PHONY : taller_editor

# fast build rule for target.
taller_editor/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_editor.dir/build.make CMakeFiles/taller_editor.dir/build
.PHONY : taller_editor/fast

#=============================================================================
# Target rules for targets named taller_client_autogen_timestamp_deps

# Build rule for target.
taller_client_autogen_timestamp_deps: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 taller_client_autogen_timestamp_deps
.PHONY : taller_client_autogen_timestamp_deps

# fast build rule for target.
taller_client_autogen_timestamp_deps/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_client_autogen_timestamp_deps.dir/build.make CMakeFiles/taller_client_autogen_timestamp_deps.dir/build
.PHONY : taller_client_autogen_timestamp_deps/fast

#=============================================================================
# Target rules for targets named taller_client_autogen

# Build rule for target.
taller_client_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 taller_client_autogen
.PHONY : taller_client_autogen

# fast build rule for target.
taller_client_autogen/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_client_autogen.dir/build.make CMakeFiles/taller_client_autogen.dir/build
.PHONY : taller_client_autogen/fast

#=============================================================================
# Target rules for targets named taller_editor_autogen_timestamp_deps

# Build rule for target.
taller_editor_autogen_timestamp_deps: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 taller_editor_autogen_timestamp_deps
.PHONY : taller_editor_autogen_timestamp_deps

# fast build rule for target.
taller_editor_autogen_timestamp_deps/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_editor_autogen_timestamp_deps.dir/build.make CMakeFiles/taller_editor_autogen_timestamp_deps.dir/build
.PHONY : taller_editor_autogen_timestamp_deps/fast

#=============================================================================
# Target rules for targets named taller_editor_autogen

# Build rule for target.
taller_editor_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 taller_editor_autogen
.PHONY : taller_editor_autogen

# fast build rule for target.
taller_editor_autogen/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_editor_autogen.dir/build.make CMakeFiles/taller_editor_autogen.dir/build
.PHONY : taller_editor_autogen/fast

#=============================================================================
# Target rules for targets named sdl_headers_copy

# Build rule for target.
sdl_headers_copy: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sdl_headers_copy
.PHONY : sdl_headers_copy

# fast build rule for target.
sdl_headers_copy/fast:
	$(MAKE) $(MAKESILENT) -f _deps/sdl2-build/CMakeFiles/sdl_headers_copy.dir/build.make _deps/sdl2-build/CMakeFiles/sdl_headers_copy.dir/build
.PHONY : sdl_headers_copy/fast

#=============================================================================
# Target rules for targets named SDL2main

# Build rule for target.
SDL2main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 SDL2main
.PHONY : SDL2main

# fast build rule for target.
SDL2main/fast:
	$(MAKE) $(MAKESILENT) -f _deps/sdl2-build/CMakeFiles/SDL2main.dir/build.make _deps/sdl2-build/CMakeFiles/SDL2main.dir/build
.PHONY : SDL2main/fast

#=============================================================================
# Target rules for targets named SDL2

# Build rule for target.
SDL2: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 SDL2
.PHONY : SDL2

# fast build rule for target.
SDL2/fast:
	$(MAKE) $(MAKESILENT) -f _deps/sdl2-build/CMakeFiles/SDL2.dir/build.make _deps/sdl2-build/CMakeFiles/SDL2.dir/build
.PHONY : SDL2/fast

#=============================================================================
# Target rules for targets named SDL2-static

# Build rule for target.
SDL2-static: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 SDL2-static
.PHONY : SDL2-static

# fast build rule for target.
SDL2-static/fast:
	$(MAKE) $(MAKESILENT) -f _deps/sdl2-build/CMakeFiles/SDL2-static.dir/build.make _deps/sdl2-build/CMakeFiles/SDL2-static.dir/build
.PHONY : SDL2-static/fast

#=============================================================================
# Target rules for targets named SDL2_test

# Build rule for target.
SDL2_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 SDL2_test
.PHONY : SDL2_test

# fast build rule for target.
SDL2_test/fast:
	$(MAKE) $(MAKESILENT) -f _deps/sdl2-build/CMakeFiles/SDL2_test.dir/build.make _deps/sdl2-build/CMakeFiles/SDL2_test.dir/build
.PHONY : SDL2_test/fast

#=============================================================================
# Target rules for targets named uninstall

# Build rule for target.
uninstall: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 uninstall
.PHONY : uninstall

# fast build rule for target.
uninstall/fast:
	$(MAKE) $(MAKESILENT) -f _deps/sdl2-build/CMakeFiles/uninstall.dir/build.make _deps/sdl2-build/CMakeFiles/uninstall.dir/build
.PHONY : uninstall/fast

#=============================================================================
# Target rules for targets named SDL2main_autogen_timestamp_deps

# Build rule for target.
SDL2main_autogen_timestamp_deps: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 SDL2main_autogen_timestamp_deps
.PHONY : SDL2main_autogen_timestamp_deps

# fast build rule for target.
SDL2main_autogen_timestamp_deps/fast:
	$(MAKE) $(MAKESILENT) -f _deps/sdl2-build/CMakeFiles/SDL2main_autogen_timestamp_deps.dir/build.make _deps/sdl2-build/CMakeFiles/SDL2main_autogen_timestamp_deps.dir/build
.PHONY : SDL2main_autogen_timestamp_deps/fast

#=============================================================================
# Target rules for targets named SDL2main_autogen

# Build rule for target.
SDL2main_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 SDL2main_autogen
.PHONY : SDL2main_autogen

# fast build rule for target.
SDL2main_autogen/fast:
	$(MAKE) $(MAKESILENT) -f _deps/sdl2-build/CMakeFiles/SDL2main_autogen.dir/build.make _deps/sdl2-build/CMakeFiles/SDL2main_autogen.dir/build
.PHONY : SDL2main_autogen/fast

#=============================================================================
# Target rules for targets named SDL2_autogen_timestamp_deps

# Build rule for target.
SDL2_autogen_timestamp_deps: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 SDL2_autogen_timestamp_deps
.PHONY : SDL2_autogen_timestamp_deps

# fast build rule for target.
SDL2_autogen_timestamp_deps/fast:
	$(MAKE) $(MAKESILENT) -f _deps/sdl2-build/CMakeFiles/SDL2_autogen_timestamp_deps.dir/build.make _deps/sdl2-build/CMakeFiles/SDL2_autogen_timestamp_deps.dir/build
.PHONY : SDL2_autogen_timestamp_deps/fast

#=============================================================================
# Target rules for targets named SDL2_autogen

# Build rule for target.
SDL2_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 SDL2_autogen
.PHONY : SDL2_autogen

# fast build rule for target.
SDL2_autogen/fast:
	$(MAKE) $(MAKESILENT) -f _deps/sdl2-build/CMakeFiles/SDL2_autogen.dir/build.make _deps/sdl2-build/CMakeFiles/SDL2_autogen.dir/build
.PHONY : SDL2_autogen/fast

#=============================================================================
# Target rules for targets named SDL2-static_autogen_timestamp_deps

# Build rule for target.
SDL2-static_autogen_timestamp_deps: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 SDL2-static_autogen_timestamp_deps
.PHONY : SDL2-static_autogen_timestamp_deps

# fast build rule for target.
SDL2-static_autogen_timestamp_deps/fast:
	$(MAKE) $(MAKESILENT) -f _deps/sdl2-build/CMakeFiles/SDL2-static_autogen_timestamp_deps.dir/build.make _deps/sdl2-build/CMakeFiles/SDL2-static_autogen_timestamp_deps.dir/build
.PHONY : SDL2-static_autogen_timestamp_deps/fast

#=============================================================================
# Target rules for targets named SDL2-static_autogen

# Build rule for target.
SDL2-static_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 SDL2-static_autogen
.PHONY : SDL2-static_autogen

# fast build rule for target.
SDL2-static_autogen/fast:
	$(MAKE) $(MAKESILENT) -f _deps/sdl2-build/CMakeFiles/SDL2-static_autogen.dir/build.make _deps/sdl2-build/CMakeFiles/SDL2-static_autogen.dir/build
.PHONY : SDL2-static_autogen/fast

#=============================================================================
# Target rules for targets named SDL2_test_autogen_timestamp_deps

# Build rule for target.
SDL2_test_autogen_timestamp_deps: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 SDL2_test_autogen_timestamp_deps
.PHONY : SDL2_test_autogen_timestamp_deps

# fast build rule for target.
SDL2_test_autogen_timestamp_deps/fast:
	$(MAKE) $(MAKESILENT) -f _deps/sdl2-build/CMakeFiles/SDL2_test_autogen_timestamp_deps.dir/build.make _deps/sdl2-build/CMakeFiles/SDL2_test_autogen_timestamp_deps.dir/build
.PHONY : SDL2_test_autogen_timestamp_deps/fast

#=============================================================================
# Target rules for targets named SDL2_test_autogen

# Build rule for target.
SDL2_test_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 SDL2_test_autogen
.PHONY : SDL2_test_autogen

# fast build rule for target.
SDL2_test_autogen/fast:
	$(MAKE) $(MAKESILENT) -f _deps/sdl2-build/CMakeFiles/SDL2_test_autogen.dir/build.make _deps/sdl2-build/CMakeFiles/SDL2_test_autogen.dir/build
.PHONY : SDL2_test_autogen/fast

#=============================================================================
# Target rules for targets named SDL2_image

# Build rule for target.
SDL2_image: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 SDL2_image
.PHONY : SDL2_image

# fast build rule for target.
SDL2_image/fast:
	$(MAKE) $(MAKESILENT) -f _deps/sdl2_image-build/CMakeFiles/SDL2_image.dir/build.make _deps/sdl2_image-build/CMakeFiles/SDL2_image.dir/build
.PHONY : SDL2_image/fast

#=============================================================================
# Target rules for targets named SDL2_image_autogen_timestamp_deps

# Build rule for target.
SDL2_image_autogen_timestamp_deps: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 SDL2_image_autogen_timestamp_deps
.PHONY : SDL2_image_autogen_timestamp_deps

# fast build rule for target.
SDL2_image_autogen_timestamp_deps/fast:
	$(MAKE) $(MAKESILENT) -f _deps/sdl2_image-build/CMakeFiles/SDL2_image_autogen_timestamp_deps.dir/build.make _deps/sdl2_image-build/CMakeFiles/SDL2_image_autogen_timestamp_deps.dir/build
.PHONY : SDL2_image_autogen_timestamp_deps/fast

#=============================================================================
# Target rules for targets named SDL2_image_autogen

# Build rule for target.
SDL2_image_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 SDL2_image_autogen
.PHONY : SDL2_image_autogen

# fast build rule for target.
SDL2_image_autogen/fast:
	$(MAKE) $(MAKESILENT) -f _deps/sdl2_image-build/CMakeFiles/SDL2_image_autogen.dir/build.make _deps/sdl2_image-build/CMakeFiles/SDL2_image_autogen.dir/build
.PHONY : SDL2_image_autogen/fast

#=============================================================================
# Target rules for targets named SDL2_mixer

# Build rule for target.
SDL2_mixer: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 SDL2_mixer
.PHONY : SDL2_mixer

# fast build rule for target.
SDL2_mixer/fast:
	$(MAKE) $(MAKESILENT) -f _deps/sdl2_mixer-build/CMakeFiles/SDL2_mixer.dir/build.make _deps/sdl2_mixer-build/CMakeFiles/SDL2_mixer.dir/build
.PHONY : SDL2_mixer/fast

#=============================================================================
# Target rules for targets named SDL2_mixer_autogen_timestamp_deps

# Build rule for target.
SDL2_mixer_autogen_timestamp_deps: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 SDL2_mixer_autogen_timestamp_deps
.PHONY : SDL2_mixer_autogen_timestamp_deps

# fast build rule for target.
SDL2_mixer_autogen_timestamp_deps/fast:
	$(MAKE) $(MAKESILENT) -f _deps/sdl2_mixer-build/CMakeFiles/SDL2_mixer_autogen_timestamp_deps.dir/build.make _deps/sdl2_mixer-build/CMakeFiles/SDL2_mixer_autogen_timestamp_deps.dir/build
.PHONY : SDL2_mixer_autogen_timestamp_deps/fast

#=============================================================================
# Target rules for targets named SDL2_mixer_autogen

# Build rule for target.
SDL2_mixer_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 SDL2_mixer_autogen
.PHONY : SDL2_mixer_autogen

# fast build rule for target.
SDL2_mixer_autogen/fast:
	$(MAKE) $(MAKESILENT) -f _deps/sdl2_mixer-build/CMakeFiles/SDL2_mixer_autogen.dir/build.make _deps/sdl2_mixer-build/CMakeFiles/SDL2_mixer_autogen.dir/build
.PHONY : SDL2_mixer_autogen/fast

#=============================================================================
# Target rules for targets named SDL2_ttf

# Build rule for target.
SDL2_ttf: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 SDL2_ttf
.PHONY : SDL2_ttf

# fast build rule for target.
SDL2_ttf/fast:
	$(MAKE) $(MAKESILENT) -f _deps/sdl2_ttf-build/CMakeFiles/SDL2_ttf.dir/build.make _deps/sdl2_ttf-build/CMakeFiles/SDL2_ttf.dir/build
.PHONY : SDL2_ttf/fast

#=============================================================================
# Target rules for targets named SDL2_ttf_autogen_timestamp_deps

# Build rule for target.
SDL2_ttf_autogen_timestamp_deps: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 SDL2_ttf_autogen_timestamp_deps
.PHONY : SDL2_ttf_autogen_timestamp_deps

# fast build rule for target.
SDL2_ttf_autogen_timestamp_deps/fast:
	$(MAKE) $(MAKESILENT) -f _deps/sdl2_ttf-build/CMakeFiles/SDL2_ttf_autogen_timestamp_deps.dir/build.make _deps/sdl2_ttf-build/CMakeFiles/SDL2_ttf_autogen_timestamp_deps.dir/build
.PHONY : SDL2_ttf_autogen_timestamp_deps/fast

#=============================================================================
# Target rules for targets named SDL2_ttf_autogen

# Build rule for target.
SDL2_ttf_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 SDL2_ttf_autogen
.PHONY : SDL2_ttf_autogen

# fast build rule for target.
SDL2_ttf_autogen/fast:
	$(MAKE) $(MAKESILENT) -f _deps/sdl2_ttf-build/CMakeFiles/SDL2_ttf_autogen.dir/build.make _deps/sdl2_ttf-build/CMakeFiles/SDL2_ttf_autogen.dir/build
.PHONY : SDL2_ttf_autogen/fast

#=============================================================================
# Target rules for targets named SDL2pp

# Build rule for target.
SDL2pp: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 SDL2pp
.PHONY : SDL2pp

# fast build rule for target.
SDL2pp/fast:
	$(MAKE) $(MAKESILENT) -f _deps/libsdl2pp-build/CMakeFiles/SDL2pp.dir/build.make _deps/libsdl2pp-build/CMakeFiles/SDL2pp.dir/build
.PHONY : SDL2pp/fast

#=============================================================================
# Target rules for targets named SDL2pp_autogen_timestamp_deps

# Build rule for target.
SDL2pp_autogen_timestamp_deps: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 SDL2pp_autogen_timestamp_deps
.PHONY : SDL2pp_autogen_timestamp_deps

# fast build rule for target.
SDL2pp_autogen_timestamp_deps/fast:
	$(MAKE) $(MAKESILENT) -f _deps/libsdl2pp-build/CMakeFiles/SDL2pp_autogen_timestamp_deps.dir/build.make _deps/libsdl2pp-build/CMakeFiles/SDL2pp_autogen_timestamp_deps.dir/build
.PHONY : SDL2pp_autogen_timestamp_deps/fast

#=============================================================================
# Target rules for targets named SDL2pp_autogen

# Build rule for target.
SDL2pp_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 SDL2pp_autogen
.PHONY : SDL2pp_autogen

# fast build rule for target.
SDL2pp_autogen/fast:
	$(MAKE) $(MAKESILENT) -f _deps/libsdl2pp-build/CMakeFiles/SDL2pp_autogen.dir/build.make _deps/libsdl2pp-build/CMakeFiles/SDL2pp_autogen.dir/build
.PHONY : SDL2pp_autogen/fast

#=============================================================================
# Target rules for targets named Experimental

# Build rule for target.
Experimental: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Experimental
.PHONY : Experimental

# fast build rule for target.
Experimental/fast:
	$(MAKE) $(MAKESILENT) -f _deps/yaml-cpp-build/CMakeFiles/Experimental.dir/build.make _deps/yaml-cpp-build/CMakeFiles/Experimental.dir/build
.PHONY : Experimental/fast

#=============================================================================
# Target rules for targets named Nightly

# Build rule for target.
Nightly: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Nightly
.PHONY : Nightly

# fast build rule for target.
Nightly/fast:
	$(MAKE) $(MAKESILENT) -f _deps/yaml-cpp-build/CMakeFiles/Nightly.dir/build.make _deps/yaml-cpp-build/CMakeFiles/Nightly.dir/build
.PHONY : Nightly/fast

#=============================================================================
# Target rules for targets named Continuous

# Build rule for target.
Continuous: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Continuous
.PHONY : Continuous

# fast build rule for target.
Continuous/fast:
	$(MAKE) $(MAKESILENT) -f _deps/yaml-cpp-build/CMakeFiles/Continuous.dir/build.make _deps/yaml-cpp-build/CMakeFiles/Continuous.dir/build
.PHONY : Continuous/fast

#=============================================================================
# Target rules for targets named NightlyMemoryCheck

# Build rule for target.
NightlyMemoryCheck: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyMemoryCheck
.PHONY : NightlyMemoryCheck

# fast build rule for target.
NightlyMemoryCheck/fast:
	$(MAKE) $(MAKESILENT) -f _deps/yaml-cpp-build/CMakeFiles/NightlyMemoryCheck.dir/build.make _deps/yaml-cpp-build/CMakeFiles/NightlyMemoryCheck.dir/build
.PHONY : NightlyMemoryCheck/fast

#=============================================================================
# Target rules for targets named NightlyStart

# Build rule for target.
NightlyStart: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyStart
.PHONY : NightlyStart

# fast build rule for target.
NightlyStart/fast:
	$(MAKE) $(MAKESILENT) -f _deps/yaml-cpp-build/CMakeFiles/NightlyStart.dir/build.make _deps/yaml-cpp-build/CMakeFiles/NightlyStart.dir/build
.PHONY : NightlyStart/fast

#=============================================================================
# Target rules for targets named NightlyUpdate

# Build rule for target.
NightlyUpdate: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyUpdate
.PHONY : NightlyUpdate

# fast build rule for target.
NightlyUpdate/fast:
	$(MAKE) $(MAKESILENT) -f _deps/yaml-cpp-build/CMakeFiles/NightlyUpdate.dir/build.make _deps/yaml-cpp-build/CMakeFiles/NightlyUpdate.dir/build
.PHONY : NightlyUpdate/fast

#=============================================================================
# Target rules for targets named NightlyConfigure

# Build rule for target.
NightlyConfigure: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyConfigure
.PHONY : NightlyConfigure

# fast build rule for target.
NightlyConfigure/fast:
	$(MAKE) $(MAKESILENT) -f _deps/yaml-cpp-build/CMakeFiles/NightlyConfigure.dir/build.make _deps/yaml-cpp-build/CMakeFiles/NightlyConfigure.dir/build
.PHONY : NightlyConfigure/fast

#=============================================================================
# Target rules for targets named NightlyBuild

# Build rule for target.
NightlyBuild: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyBuild
.PHONY : NightlyBuild

# fast build rule for target.
NightlyBuild/fast:
	$(MAKE) $(MAKESILENT) -f _deps/yaml-cpp-build/CMakeFiles/NightlyBuild.dir/build.make _deps/yaml-cpp-build/CMakeFiles/NightlyBuild.dir/build
.PHONY : NightlyBuild/fast

#=============================================================================
# Target rules for targets named NightlyTest

# Build rule for target.
NightlyTest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyTest
.PHONY : NightlyTest

# fast build rule for target.
NightlyTest/fast:
	$(MAKE) $(MAKESILENT) -f _deps/yaml-cpp-build/CMakeFiles/NightlyTest.dir/build.make _deps/yaml-cpp-build/CMakeFiles/NightlyTest.dir/build
.PHONY : NightlyTest/fast

#=============================================================================
# Target rules for targets named NightlyCoverage

# Build rule for target.
NightlyCoverage: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyCoverage
.PHONY : NightlyCoverage

# fast build rule for target.
NightlyCoverage/fast:
	$(MAKE) $(MAKESILENT) -f _deps/yaml-cpp-build/CMakeFiles/NightlyCoverage.dir/build.make _deps/yaml-cpp-build/CMakeFiles/NightlyCoverage.dir/build
.PHONY : NightlyCoverage/fast

#=============================================================================
# Target rules for targets named NightlyMemCheck

# Build rule for target.
NightlyMemCheck: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyMemCheck
.PHONY : NightlyMemCheck

# fast build rule for target.
NightlyMemCheck/fast:
	$(MAKE) $(MAKESILENT) -f _deps/yaml-cpp-build/CMakeFiles/NightlyMemCheck.dir/build.make _deps/yaml-cpp-build/CMakeFiles/NightlyMemCheck.dir/build
.PHONY : NightlyMemCheck/fast

#=============================================================================
# Target rules for targets named NightlySubmit

# Build rule for target.
NightlySubmit: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlySubmit
.PHONY : NightlySubmit

# fast build rule for target.
NightlySubmit/fast:
	$(MAKE) $(MAKESILENT) -f _deps/yaml-cpp-build/CMakeFiles/NightlySubmit.dir/build.make _deps/yaml-cpp-build/CMakeFiles/NightlySubmit.dir/build
.PHONY : NightlySubmit/fast

#=============================================================================
# Target rules for targets named ExperimentalStart

# Build rule for target.
ExperimentalStart: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalStart
.PHONY : ExperimentalStart

# fast build rule for target.
ExperimentalStart/fast:
	$(MAKE) $(MAKESILENT) -f _deps/yaml-cpp-build/CMakeFiles/ExperimentalStart.dir/build.make _deps/yaml-cpp-build/CMakeFiles/ExperimentalStart.dir/build
.PHONY : ExperimentalStart/fast

#=============================================================================
# Target rules for targets named ExperimentalUpdate

# Build rule for target.
ExperimentalUpdate: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalUpdate
.PHONY : ExperimentalUpdate

# fast build rule for target.
ExperimentalUpdate/fast:
	$(MAKE) $(MAKESILENT) -f _deps/yaml-cpp-build/CMakeFiles/ExperimentalUpdate.dir/build.make _deps/yaml-cpp-build/CMakeFiles/ExperimentalUpdate.dir/build
.PHONY : ExperimentalUpdate/fast

#=============================================================================
# Target rules for targets named ExperimentalConfigure

# Build rule for target.
ExperimentalConfigure: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalConfigure
.PHONY : ExperimentalConfigure

# fast build rule for target.
ExperimentalConfigure/fast:
	$(MAKE) $(MAKESILENT) -f _deps/yaml-cpp-build/CMakeFiles/ExperimentalConfigure.dir/build.make _deps/yaml-cpp-build/CMakeFiles/ExperimentalConfigure.dir/build
.PHONY : ExperimentalConfigure/fast

#=============================================================================
# Target rules for targets named ExperimentalBuild

# Build rule for target.
ExperimentalBuild: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalBuild
.PHONY : ExperimentalBuild

# fast build rule for target.
ExperimentalBuild/fast:
	$(MAKE) $(MAKESILENT) -f _deps/yaml-cpp-build/CMakeFiles/ExperimentalBuild.dir/build.make _deps/yaml-cpp-build/CMakeFiles/ExperimentalBuild.dir/build
.PHONY : ExperimentalBuild/fast

#=============================================================================
# Target rules for targets named ExperimentalTest

# Build rule for target.
ExperimentalTest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalTest
.PHONY : ExperimentalTest

# fast build rule for target.
ExperimentalTest/fast:
	$(MAKE) $(MAKESILENT) -f _deps/yaml-cpp-build/CMakeFiles/ExperimentalTest.dir/build.make _deps/yaml-cpp-build/CMakeFiles/ExperimentalTest.dir/build
.PHONY : ExperimentalTest/fast

#=============================================================================
# Target rules for targets named ExperimentalCoverage

# Build rule for target.
ExperimentalCoverage: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalCoverage
.PHONY : ExperimentalCoverage

# fast build rule for target.
ExperimentalCoverage/fast:
	$(MAKE) $(MAKESILENT) -f _deps/yaml-cpp-build/CMakeFiles/ExperimentalCoverage.dir/build.make _deps/yaml-cpp-build/CMakeFiles/ExperimentalCoverage.dir/build
.PHONY : ExperimentalCoverage/fast

#=============================================================================
# Target rules for targets named ExperimentalMemCheck

# Build rule for target.
ExperimentalMemCheck: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalMemCheck
.PHONY : ExperimentalMemCheck

# fast build rule for target.
ExperimentalMemCheck/fast:
	$(MAKE) $(MAKESILENT) -f _deps/yaml-cpp-build/CMakeFiles/ExperimentalMemCheck.dir/build.make _deps/yaml-cpp-build/CMakeFiles/ExperimentalMemCheck.dir/build
.PHONY : ExperimentalMemCheck/fast

#=============================================================================
# Target rules for targets named ExperimentalSubmit

# Build rule for target.
ExperimentalSubmit: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalSubmit
.PHONY : ExperimentalSubmit

# fast build rule for target.
ExperimentalSubmit/fast:
	$(MAKE) $(MAKESILENT) -f _deps/yaml-cpp-build/CMakeFiles/ExperimentalSubmit.dir/build.make _deps/yaml-cpp-build/CMakeFiles/ExperimentalSubmit.dir/build
.PHONY : ExperimentalSubmit/fast

#=============================================================================
# Target rules for targets named ContinuousStart

# Build rule for target.
ContinuousStart: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousStart
.PHONY : ContinuousStart

# fast build rule for target.
ContinuousStart/fast:
	$(MAKE) $(MAKESILENT) -f _deps/yaml-cpp-build/CMakeFiles/ContinuousStart.dir/build.make _deps/yaml-cpp-build/CMakeFiles/ContinuousStart.dir/build
.PHONY : ContinuousStart/fast

#=============================================================================
# Target rules for targets named ContinuousUpdate

# Build rule for target.
ContinuousUpdate: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousUpdate
.PHONY : ContinuousUpdate

# fast build rule for target.
ContinuousUpdate/fast:
	$(MAKE) $(MAKESILENT) -f _deps/yaml-cpp-build/CMakeFiles/ContinuousUpdate.dir/build.make _deps/yaml-cpp-build/CMakeFiles/ContinuousUpdate.dir/build
.PHONY : ContinuousUpdate/fast

#=============================================================================
# Target rules for targets named ContinuousConfigure

# Build rule for target.
ContinuousConfigure: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousConfigure
.PHONY : ContinuousConfigure

# fast build rule for target.
ContinuousConfigure/fast:
	$(MAKE) $(MAKESILENT) -f _deps/yaml-cpp-build/CMakeFiles/ContinuousConfigure.dir/build.make _deps/yaml-cpp-build/CMakeFiles/ContinuousConfigure.dir/build
.PHONY : ContinuousConfigure/fast

#=============================================================================
# Target rules for targets named ContinuousBuild

# Build rule for target.
ContinuousBuild: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousBuild
.PHONY : ContinuousBuild

# fast build rule for target.
ContinuousBuild/fast:
	$(MAKE) $(MAKESILENT) -f _deps/yaml-cpp-build/CMakeFiles/ContinuousBuild.dir/build.make _deps/yaml-cpp-build/CMakeFiles/ContinuousBuild.dir/build
.PHONY : ContinuousBuild/fast

#=============================================================================
# Target rules for targets named ContinuousTest

# Build rule for target.
ContinuousTest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousTest
.PHONY : ContinuousTest

# fast build rule for target.
ContinuousTest/fast:
	$(MAKE) $(MAKESILENT) -f _deps/yaml-cpp-build/CMakeFiles/ContinuousTest.dir/build.make _deps/yaml-cpp-build/CMakeFiles/ContinuousTest.dir/build
.PHONY : ContinuousTest/fast

#=============================================================================
# Target rules for targets named ContinuousCoverage

# Build rule for target.
ContinuousCoverage: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousCoverage
.PHONY : ContinuousCoverage

# fast build rule for target.
ContinuousCoverage/fast:
	$(MAKE) $(MAKESILENT) -f _deps/yaml-cpp-build/CMakeFiles/ContinuousCoverage.dir/build.make _deps/yaml-cpp-build/CMakeFiles/ContinuousCoverage.dir/build
.PHONY : ContinuousCoverage/fast

#=============================================================================
# Target rules for targets named ContinuousMemCheck

# Build rule for target.
ContinuousMemCheck: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousMemCheck
.PHONY : ContinuousMemCheck

# fast build rule for target.
ContinuousMemCheck/fast:
	$(MAKE) $(MAKESILENT) -f _deps/yaml-cpp-build/CMakeFiles/ContinuousMemCheck.dir/build.make _deps/yaml-cpp-build/CMakeFiles/ContinuousMemCheck.dir/build
.PHONY : ContinuousMemCheck/fast

#=============================================================================
# Target rules for targets named ContinuousSubmit

# Build rule for target.
ContinuousSubmit: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousSubmit
.PHONY : ContinuousSubmit

# fast build rule for target.
ContinuousSubmit/fast:
	$(MAKE) $(MAKESILENT) -f _deps/yaml-cpp-build/CMakeFiles/ContinuousSubmit.dir/build.make _deps/yaml-cpp-build/CMakeFiles/ContinuousSubmit.dir/build
.PHONY : ContinuousSubmit/fast

#=============================================================================
# Target rules for targets named yaml-cpp

# Build rule for target.
yaml-cpp: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 yaml-cpp
.PHONY : yaml-cpp

# fast build rule for target.
yaml-cpp/fast:
	$(MAKE) $(MAKESILENT) -f _deps/yaml-cpp-build/CMakeFiles/yaml-cpp.dir/build.make _deps/yaml-cpp-build/CMakeFiles/yaml-cpp.dir/build
.PHONY : yaml-cpp/fast

#=============================================================================
# Target rules for targets named format

# Build rule for target.
format: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 format
.PHONY : format

# fast build rule for target.
format/fast:
	$(MAKE) $(MAKESILENT) -f _deps/yaml-cpp-build/CMakeFiles/format.dir/build.make _deps/yaml-cpp-build/CMakeFiles/format.dir/build
.PHONY : format/fast

#=============================================================================
# Target rules for targets named yaml-cpp_autogen_timestamp_deps

# Build rule for target.
yaml-cpp_autogen_timestamp_deps: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 yaml-cpp_autogen_timestamp_deps
.PHONY : yaml-cpp_autogen_timestamp_deps

# fast build rule for target.
yaml-cpp_autogen_timestamp_deps/fast:
	$(MAKE) $(MAKESILENT) -f _deps/yaml-cpp-build/CMakeFiles/yaml-cpp_autogen_timestamp_deps.dir/build.make _deps/yaml-cpp-build/CMakeFiles/yaml-cpp_autogen_timestamp_deps.dir/build
.PHONY : yaml-cpp_autogen_timestamp_deps/fast

#=============================================================================
# Target rules for targets named yaml-cpp_autogen

# Build rule for target.
yaml-cpp_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 yaml-cpp_autogen
.PHONY : yaml-cpp_autogen

# fast build rule for target.
yaml-cpp_autogen/fast:
	$(MAKE) $(MAKESILENT) -f _deps/yaml-cpp-build/CMakeFiles/yaml-cpp_autogen.dir/build.make _deps/yaml-cpp-build/CMakeFiles/yaml-cpp_autogen.dir/build
.PHONY : yaml-cpp_autogen/fast

#=============================================================================
# Target rules for targets named yaml-cpp-sandbox

# Build rule for target.
yaml-cpp-sandbox: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 yaml-cpp-sandbox
.PHONY : yaml-cpp-sandbox

# fast build rule for target.
yaml-cpp-sandbox/fast:
	$(MAKE) $(MAKESILENT) -f _deps/yaml-cpp-build/util/CMakeFiles/yaml-cpp-sandbox.dir/build.make _deps/yaml-cpp-build/util/CMakeFiles/yaml-cpp-sandbox.dir/build
.PHONY : yaml-cpp-sandbox/fast

#=============================================================================
# Target rules for targets named yaml-cpp-parse

# Build rule for target.
yaml-cpp-parse: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 yaml-cpp-parse
.PHONY : yaml-cpp-parse

# fast build rule for target.
yaml-cpp-parse/fast:
	$(MAKE) $(MAKESILENT) -f _deps/yaml-cpp-build/util/CMakeFiles/yaml-cpp-parse.dir/build.make _deps/yaml-cpp-build/util/CMakeFiles/yaml-cpp-parse.dir/build
.PHONY : yaml-cpp-parse/fast

#=============================================================================
# Target rules for targets named yaml-cpp-read

# Build rule for target.
yaml-cpp-read: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 yaml-cpp-read
.PHONY : yaml-cpp-read

# fast build rule for target.
yaml-cpp-read/fast:
	$(MAKE) $(MAKESILENT) -f _deps/yaml-cpp-build/util/CMakeFiles/yaml-cpp-read.dir/build.make _deps/yaml-cpp-build/util/CMakeFiles/yaml-cpp-read.dir/build
.PHONY : yaml-cpp-read/fast

#=============================================================================
# Target rules for targets named yaml-cpp-sandbox_autogen_timestamp_deps

# Build rule for target.
yaml-cpp-sandbox_autogen_timestamp_deps: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 yaml-cpp-sandbox_autogen_timestamp_deps
.PHONY : yaml-cpp-sandbox_autogen_timestamp_deps

# fast build rule for target.
yaml-cpp-sandbox_autogen_timestamp_deps/fast:
	$(MAKE) $(MAKESILENT) -f _deps/yaml-cpp-build/util/CMakeFiles/yaml-cpp-sandbox_autogen_timestamp_deps.dir/build.make _deps/yaml-cpp-build/util/CMakeFiles/yaml-cpp-sandbox_autogen_timestamp_deps.dir/build
.PHONY : yaml-cpp-sandbox_autogen_timestamp_deps/fast

#=============================================================================
# Target rules for targets named yaml-cpp-sandbox_autogen

# Build rule for target.
yaml-cpp-sandbox_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 yaml-cpp-sandbox_autogen
.PHONY : yaml-cpp-sandbox_autogen

# fast build rule for target.
yaml-cpp-sandbox_autogen/fast:
	$(MAKE) $(MAKESILENT) -f _deps/yaml-cpp-build/util/CMakeFiles/yaml-cpp-sandbox_autogen.dir/build.make _deps/yaml-cpp-build/util/CMakeFiles/yaml-cpp-sandbox_autogen.dir/build
.PHONY : yaml-cpp-sandbox_autogen/fast

#=============================================================================
# Target rules for targets named yaml-cpp-parse_autogen_timestamp_deps

# Build rule for target.
yaml-cpp-parse_autogen_timestamp_deps: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 yaml-cpp-parse_autogen_timestamp_deps
.PHONY : yaml-cpp-parse_autogen_timestamp_deps

# fast build rule for target.
yaml-cpp-parse_autogen_timestamp_deps/fast:
	$(MAKE) $(MAKESILENT) -f _deps/yaml-cpp-build/util/CMakeFiles/yaml-cpp-parse_autogen_timestamp_deps.dir/build.make _deps/yaml-cpp-build/util/CMakeFiles/yaml-cpp-parse_autogen_timestamp_deps.dir/build
.PHONY : yaml-cpp-parse_autogen_timestamp_deps/fast

#=============================================================================
# Target rules for targets named yaml-cpp-parse_autogen

# Build rule for target.
yaml-cpp-parse_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 yaml-cpp-parse_autogen
.PHONY : yaml-cpp-parse_autogen

# fast build rule for target.
yaml-cpp-parse_autogen/fast:
	$(MAKE) $(MAKESILENT) -f _deps/yaml-cpp-build/util/CMakeFiles/yaml-cpp-parse_autogen.dir/build.make _deps/yaml-cpp-build/util/CMakeFiles/yaml-cpp-parse_autogen.dir/build
.PHONY : yaml-cpp-parse_autogen/fast

#=============================================================================
# Target rules for targets named yaml-cpp-read_autogen_timestamp_deps

# Build rule for target.
yaml-cpp-read_autogen_timestamp_deps: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 yaml-cpp-read_autogen_timestamp_deps
.PHONY : yaml-cpp-read_autogen_timestamp_deps

# fast build rule for target.
yaml-cpp-read_autogen_timestamp_deps/fast:
	$(MAKE) $(MAKESILENT) -f _deps/yaml-cpp-build/util/CMakeFiles/yaml-cpp-read_autogen_timestamp_deps.dir/build.make _deps/yaml-cpp-build/util/CMakeFiles/yaml-cpp-read_autogen_timestamp_deps.dir/build
.PHONY : yaml-cpp-read_autogen_timestamp_deps/fast

#=============================================================================
# Target rules for targets named yaml-cpp-read_autogen

# Build rule for target.
yaml-cpp-read_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 yaml-cpp-read_autogen
.PHONY : yaml-cpp-read_autogen

# fast build rule for target.
yaml-cpp-read_autogen/fast:
	$(MAKE) $(MAKESILENT) -f _deps/yaml-cpp-build/util/CMakeFiles/yaml-cpp-read_autogen.dir/build.make _deps/yaml-cpp-build/util/CMakeFiles/yaml-cpp-read_autogen.dir/build
.PHONY : yaml-cpp-read_autogen/fast

client/Pantallas/carselectscreen.o: client/Pantallas/carselectscreen.cpp.o
.PHONY : client/Pantallas/carselectscreen.o

# target to build an object file
client/Pantallas/carselectscreen.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_client.dir/build.make CMakeFiles/taller_client.dir/client/Pantallas/carselectscreen.cpp.o
.PHONY : client/Pantallas/carselectscreen.cpp.o

client/Pantallas/carselectscreen.i: client/Pantallas/carselectscreen.cpp.i
.PHONY : client/Pantallas/carselectscreen.i

# target to preprocess a source file
client/Pantallas/carselectscreen.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_client.dir/build.make CMakeFiles/taller_client.dir/client/Pantallas/carselectscreen.cpp.i
.PHONY : client/Pantallas/carselectscreen.cpp.i

client/Pantallas/carselectscreen.s: client/Pantallas/carselectscreen.cpp.s
.PHONY : client/Pantallas/carselectscreen.s

# target to generate assembly for a file
client/Pantallas/carselectscreen.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_client.dir/build.make CMakeFiles/taller_client.dir/client/Pantallas/carselectscreen.cpp.s
.PHONY : client/Pantallas/carselectscreen.cpp.s

client/Pantallas/lobbyscreen.o: client/Pantallas/lobbyscreen.cpp.o
.PHONY : client/Pantallas/lobbyscreen.o

# target to build an object file
client/Pantallas/lobbyscreen.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_client.dir/build.make CMakeFiles/taller_client.dir/client/Pantallas/lobbyscreen.cpp.o
.PHONY : client/Pantallas/lobbyscreen.cpp.o

client/Pantallas/lobbyscreen.i: client/Pantallas/lobbyscreen.cpp.i
.PHONY : client/Pantallas/lobbyscreen.i

# target to preprocess a source file
client/Pantallas/lobbyscreen.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_client.dir/build.make CMakeFiles/taller_client.dir/client/Pantallas/lobbyscreen.cpp.i
.PHONY : client/Pantallas/lobbyscreen.cpp.i

client/Pantallas/lobbyscreen.s: client/Pantallas/lobbyscreen.cpp.s
.PHONY : client/Pantallas/lobbyscreen.s

# target to generate assembly for a file
client/Pantallas/lobbyscreen.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_client.dir/build.make CMakeFiles/taller_client.dir/client/Pantallas/lobbyscreen.cpp.s
.PHONY : client/Pantallas/lobbyscreen.cpp.s

client/Pantallas/loginscreen.o: client/Pantallas/loginscreen.cpp.o
.PHONY : client/Pantallas/loginscreen.o

# target to build an object file
client/Pantallas/loginscreen.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_client.dir/build.make CMakeFiles/taller_client.dir/client/Pantallas/loginscreen.cpp.o
.PHONY : client/Pantallas/loginscreen.cpp.o

client/Pantallas/loginscreen.i: client/Pantallas/loginscreen.cpp.i
.PHONY : client/Pantallas/loginscreen.i

# target to preprocess a source file
client/Pantallas/loginscreen.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_client.dir/build.make CMakeFiles/taller_client.dir/client/Pantallas/loginscreen.cpp.i
.PHONY : client/Pantallas/loginscreen.cpp.i

client/Pantallas/loginscreen.s: client/Pantallas/loginscreen.cpp.s
.PHONY : client/Pantallas/loginscreen.s

# target to generate assembly for a file
client/Pantallas/loginscreen.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_client.dir/build.make CMakeFiles/taller_client.dir/client/Pantallas/loginscreen.cpp.s
.PHONY : client/Pantallas/loginscreen.cpp.s

client/client.o: client/client.cpp.o
.PHONY : client/client.o

# target to build an object file
client/client.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_client.dir/build.make CMakeFiles/taller_client.dir/client/client.cpp.o
.PHONY : client/client.cpp.o

client/client.i: client/client.cpp.i
.PHONY : client/client.i

# target to preprocess a source file
client/client.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_client.dir/build.make CMakeFiles/taller_client.dir/client/client.cpp.i
.PHONY : client/client.cpp.i

client/client.s: client/client.cpp.s
.PHONY : client/client.s

# target to generate assembly for a file
client/client.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_client.dir/build.make CMakeFiles/taller_client.dir/client/client.cpp.s
.PHONY : client/client.cpp.s

client/client_main.o: client/client_main.cpp.o
.PHONY : client/client_main.o

# target to build an object file
client/client_main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_client.dir/build.make CMakeFiles/taller_client.dir/client/client_main.cpp.o
.PHONY : client/client_main.cpp.o

client/client_main.i: client/client_main.cpp.i
.PHONY : client/client_main.i

# target to preprocess a source file
client/client_main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_client.dir/build.make CMakeFiles/taller_client.dir/client/client_main.cpp.i
.PHONY : client/client_main.cpp.i

client/client_main.s: client/client_main.cpp.s
.PHONY : client/client_main.s

# target to generate assembly for a file
client/client_main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_client.dir/build.make CMakeFiles/taller_client.dir/client/client_main.cpp.s
.PHONY : client/client_main.cpp.s

client/client_protocol.o: client/client_protocol.cpp.o
.PHONY : client/client_protocol.o

# target to build an object file
client/client_protocol.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_client.dir/build.make CMakeFiles/taller_client.dir/client/client_protocol.cpp.o
.PHONY : client/client_protocol.cpp.o

client/client_protocol.i: client/client_protocol.cpp.i
.PHONY : client/client_protocol.i

# target to preprocess a source file
client/client_protocol.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_client.dir/build.make CMakeFiles/taller_client.dir/client/client_protocol.cpp.i
.PHONY : client/client_protocol.cpp.i

client/client_protocol.s: client/client_protocol.cpp.s
.PHONY : client/client_protocol.s

# target to generate assembly for a file
client/client_protocol.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_client.dir/build.make CMakeFiles/taller_client.dir/client/client_protocol.cpp.s
.PHONY : client/client_protocol.cpp.s

client/client_receiver.o: client/client_receiver.cpp.o
.PHONY : client/client_receiver.o

# target to build an object file
client/client_receiver.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_client.dir/build.make CMakeFiles/taller_client.dir/client/client_receiver.cpp.o
.PHONY : client/client_receiver.cpp.o

client/client_receiver.i: client/client_receiver.cpp.i
.PHONY : client/client_receiver.i

# target to preprocess a source file
client/client_receiver.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_client.dir/build.make CMakeFiles/taller_client.dir/client/client_receiver.cpp.i
.PHONY : client/client_receiver.cpp.i

client/client_receiver.s: client/client_receiver.cpp.s
.PHONY : client/client_receiver.s

# target to generate assembly for a file
client/client_receiver.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_client.dir/build.make CMakeFiles/taller_client.dir/client/client_receiver.cpp.s
.PHONY : client/client_receiver.cpp.s

client/client_sender.o: client/client_sender.cpp.o
.PHONY : client/client_sender.o

# target to build an object file
client/client_sender.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_client.dir/build.make CMakeFiles/taller_client.dir/client/client_sender.cpp.o
.PHONY : client/client_sender.cpp.o

client/client_sender.i: client/client_sender.cpp.i
.PHONY : client/client_sender.i

# target to preprocess a source file
client/client_sender.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_client.dir/build.make CMakeFiles/taller_client.dir/client/client_sender.cpp.i
.PHONY : client/client_sender.cpp.i

client/client_sender.s: client/client_sender.cpp.s
.PHONY : client/client_sender.s

# target to generate assembly for a file
client/client_sender.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_client.dir/build.make CMakeFiles/taller_client.dir/client/client_sender.cpp.s
.PHONY : client/client_sender.cpp.s

client/game_window.o: client/game_window.cpp.o
.PHONY : client/game_window.o

# target to build an object file
client/game_window.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_client.dir/build.make CMakeFiles/taller_client.dir/client/game_window.cpp.o
.PHONY : client/game_window.cpp.o

client/game_window.i: client/game_window.cpp.i
.PHONY : client/game_window.i

# target to preprocess a source file
client/game_window.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_client.dir/build.make CMakeFiles/taller_client.dir/client/game_window.cpp.i
.PHONY : client/game_window.cpp.i

client/game_window.s: client/game_window.cpp.s
.PHONY : client/game_window.s

# target to generate assembly for a file
client/game_window.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_client.dir/build.make CMakeFiles/taller_client.dir/client/game_window.cpp.s
.PHONY : client/game_window.cpp.s

client/mainwindow.o: client/mainwindow.cpp.o
.PHONY : client/mainwindow.o

# target to build an object file
client/mainwindow.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_client.dir/build.make CMakeFiles/taller_client.dir/client/mainwindow.cpp.o
.PHONY : client/mainwindow.cpp.o

client/mainwindow.i: client/mainwindow.cpp.i
.PHONY : client/mainwindow.i

# target to preprocess a source file
client/mainwindow.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_client.dir/build.make CMakeFiles/taller_client.dir/client/mainwindow.cpp.i
.PHONY : client/mainwindow.cpp.i

client/mainwindow.s: client/mainwindow.cpp.s
.PHONY : client/mainwindow.s

# target to generate assembly for a file
client/mainwindow.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_client.dir/build.make CMakeFiles/taller_client.dir/client/mainwindow.cpp.s
.PHONY : client/mainwindow.cpp.s

common/liberror.o: common/liberror.cpp.o
.PHONY : common/liberror.o

# target to build an object file
common/liberror.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_common.dir/build.make CMakeFiles/taller_common.dir/common/liberror.cpp.o
.PHONY : common/liberror.cpp.o

common/liberror.i: common/liberror.cpp.i
.PHONY : common/liberror.i

# target to preprocess a source file
common/liberror.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_common.dir/build.make CMakeFiles/taller_common.dir/common/liberror.cpp.i
.PHONY : common/liberror.cpp.i

common/liberror.s: common/liberror.cpp.s
.PHONY : common/liberror.s

# target to generate assembly for a file
common/liberror.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_common.dir/build.make CMakeFiles/taller_common.dir/common/liberror.cpp.s
.PHONY : common/liberror.cpp.s

common/resolver.o: common/resolver.cpp.o
.PHONY : common/resolver.o

# target to build an object file
common/resolver.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_common.dir/build.make CMakeFiles/taller_common.dir/common/resolver.cpp.o
.PHONY : common/resolver.cpp.o

common/resolver.i: common/resolver.cpp.i
.PHONY : common/resolver.i

# target to preprocess a source file
common/resolver.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_common.dir/build.make CMakeFiles/taller_common.dir/common/resolver.cpp.i
.PHONY : common/resolver.cpp.i

common/resolver.s: common/resolver.cpp.s
.PHONY : common/resolver.s

# target to generate assembly for a file
common/resolver.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_common.dir/build.make CMakeFiles/taller_common.dir/common/resolver.cpp.s
.PHONY : common/resolver.cpp.s

common/resolvererror.o: common/resolvererror.cpp.o
.PHONY : common/resolvererror.o

# target to build an object file
common/resolvererror.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_common.dir/build.make CMakeFiles/taller_common.dir/common/resolvererror.cpp.o
.PHONY : common/resolvererror.cpp.o

common/resolvererror.i: common/resolvererror.cpp.i
.PHONY : common/resolvererror.i

# target to preprocess a source file
common/resolvererror.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_common.dir/build.make CMakeFiles/taller_common.dir/common/resolvererror.cpp.i
.PHONY : common/resolvererror.cpp.i

common/resolvererror.s: common/resolvererror.cpp.s
.PHONY : common/resolvererror.s

# target to generate assembly for a file
common/resolvererror.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_common.dir/build.make CMakeFiles/taller_common.dir/common/resolvererror.cpp.s
.PHONY : common/resolvererror.cpp.s

common/socket.o: common/socket.cpp.o
.PHONY : common/socket.o

# target to build an object file
common/socket.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_common.dir/build.make CMakeFiles/taller_common.dir/common/socket.cpp.o
.PHONY : common/socket.cpp.o

common/socket.i: common/socket.cpp.i
.PHONY : common/socket.i

# target to preprocess a source file
common/socket.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_common.dir/build.make CMakeFiles/taller_common.dir/common/socket.cpp.i
.PHONY : common/socket.cpp.i

common/socket.s: common/socket.cpp.s
.PHONY : common/socket.s

# target to generate assembly for a file
common/socket.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_common.dir/build.make CMakeFiles/taller_common.dir/common/socket.cpp.s
.PHONY : common/socket.cpp.s

editor/main.o: editor/main.cpp.o
.PHONY : editor/main.o

# target to build an object file
editor/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_editor.dir/build.make CMakeFiles/taller_editor.dir/editor/main.cpp.o
.PHONY : editor/main.cpp.o

editor/main.i: editor/main.cpp.i
.PHONY : editor/main.i

# target to preprocess a source file
editor/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_editor.dir/build.make CMakeFiles/taller_editor.dir/editor/main.cpp.i
.PHONY : editor/main.cpp.i

editor/main.s: editor/main.cpp.s
.PHONY : editor/main.s

# target to generate assembly for a file
editor/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_editor.dir/build.make CMakeFiles/taller_editor.dir/editor/main.cpp.s
.PHONY : editor/main.cpp.s

editor/mainwindow.o: editor/mainwindow.cpp.o
.PHONY : editor/mainwindow.o

# target to build an object file
editor/mainwindow.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_editor.dir/build.make CMakeFiles/taller_editor.dir/editor/mainwindow.cpp.o
.PHONY : editor/mainwindow.cpp.o

editor/mainwindow.i: editor/mainwindow.cpp.i
.PHONY : editor/mainwindow.i

# target to preprocess a source file
editor/mainwindow.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_editor.dir/build.make CMakeFiles/taller_editor.dir/editor/mainwindow.cpp.i
.PHONY : editor/mainwindow.cpp.i

editor/mainwindow.s: editor/mainwindow.cpp.s
.PHONY : editor/mainwindow.s

# target to generate assembly for a file
editor/mainwindow.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_editor.dir/build.make CMakeFiles/taller_editor.dir/editor/mainwindow.cpp.s
.PHONY : editor/mainwindow.cpp.s

taller_client_autogen/mocs_compilation.o: taller_client_autogen/mocs_compilation.cpp.o
.PHONY : taller_client_autogen/mocs_compilation.o

# target to build an object file
taller_client_autogen/mocs_compilation.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_client.dir/build.make CMakeFiles/taller_client.dir/taller_client_autogen/mocs_compilation.cpp.o
.PHONY : taller_client_autogen/mocs_compilation.cpp.o

taller_client_autogen/mocs_compilation.i: taller_client_autogen/mocs_compilation.cpp.i
.PHONY : taller_client_autogen/mocs_compilation.i

# target to preprocess a source file
taller_client_autogen/mocs_compilation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_client.dir/build.make CMakeFiles/taller_client.dir/taller_client_autogen/mocs_compilation.cpp.i
.PHONY : taller_client_autogen/mocs_compilation.cpp.i

taller_client_autogen/mocs_compilation.s: taller_client_autogen/mocs_compilation.cpp.s
.PHONY : taller_client_autogen/mocs_compilation.s

# target to generate assembly for a file
taller_client_autogen/mocs_compilation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_client.dir/build.make CMakeFiles/taller_client.dir/taller_client_autogen/mocs_compilation.cpp.s
.PHONY : taller_client_autogen/mocs_compilation.cpp.s

taller_editor_autogen/mocs_compilation.o: taller_editor_autogen/mocs_compilation.cpp.o
.PHONY : taller_editor_autogen/mocs_compilation.o

# target to build an object file
taller_editor_autogen/mocs_compilation.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_editor.dir/build.make CMakeFiles/taller_editor.dir/taller_editor_autogen/mocs_compilation.cpp.o
.PHONY : taller_editor_autogen/mocs_compilation.cpp.o

taller_editor_autogen/mocs_compilation.i: taller_editor_autogen/mocs_compilation.cpp.i
.PHONY : taller_editor_autogen/mocs_compilation.i

# target to preprocess a source file
taller_editor_autogen/mocs_compilation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_editor.dir/build.make CMakeFiles/taller_editor.dir/taller_editor_autogen/mocs_compilation.cpp.i
.PHONY : taller_editor_autogen/mocs_compilation.cpp.i

taller_editor_autogen/mocs_compilation.s: taller_editor_autogen/mocs_compilation.cpp.s
.PHONY : taller_editor_autogen/mocs_compilation.s

# target to generate assembly for a file
taller_editor_autogen/mocs_compilation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_editor.dir/build.make CMakeFiles/taller_editor.dir/taller_editor_autogen/mocs_compilation.cpp.s
.PHONY : taller_editor_autogen/mocs_compilation.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... Continuous"
	@echo "... ContinuousBuild"
	@echo "... ContinuousConfigure"
	@echo "... ContinuousCoverage"
	@echo "... ContinuousMemCheck"
	@echo "... ContinuousStart"
	@echo "... ContinuousSubmit"
	@echo "... ContinuousTest"
	@echo "... ContinuousUpdate"
	@echo "... Experimental"
	@echo "... ExperimentalBuild"
	@echo "... ExperimentalConfigure"
	@echo "... ExperimentalCoverage"
	@echo "... ExperimentalMemCheck"
	@echo "... ExperimentalStart"
	@echo "... ExperimentalSubmit"
	@echo "... ExperimentalTest"
	@echo "... ExperimentalUpdate"
	@echo "... Nightly"
	@echo "... NightlyBuild"
	@echo "... NightlyConfigure"
	@echo "... NightlyCoverage"
	@echo "... NightlyMemCheck"
	@echo "... NightlyMemoryCheck"
	@echo "... NightlyStart"
	@echo "... NightlySubmit"
	@echo "... NightlyTest"
	@echo "... NightlyUpdate"
	@echo "... SDL2-static_autogen"
	@echo "... SDL2-static_autogen_timestamp_deps"
	@echo "... SDL2_autogen"
	@echo "... SDL2_autogen_timestamp_deps"
	@echo "... SDL2_image_autogen"
	@echo "... SDL2_image_autogen_timestamp_deps"
	@echo "... SDL2_mixer_autogen"
	@echo "... SDL2_mixer_autogen_timestamp_deps"
	@echo "... SDL2_test_autogen"
	@echo "... SDL2_test_autogen_timestamp_deps"
	@echo "... SDL2_ttf_autogen"
	@echo "... SDL2_ttf_autogen_timestamp_deps"
	@echo "... SDL2main_autogen"
	@echo "... SDL2main_autogen_timestamp_deps"
	@echo "... SDL2pp_autogen"
	@echo "... SDL2pp_autogen_timestamp_deps"
	@echo "... format"
	@echo "... sdl_headers_copy"
	@echo "... taller_client_autogen"
	@echo "... taller_client_autogen_timestamp_deps"
	@echo "... taller_editor_autogen"
	@echo "... taller_editor_autogen_timestamp_deps"
	@echo "... uninstall"
	@echo "... yaml-cpp-parse_autogen"
	@echo "... yaml-cpp-parse_autogen_timestamp_deps"
	@echo "... yaml-cpp-read_autogen"
	@echo "... yaml-cpp-read_autogen_timestamp_deps"
	@echo "... yaml-cpp-sandbox_autogen"
	@echo "... yaml-cpp-sandbox_autogen_timestamp_deps"
	@echo "... yaml-cpp_autogen"
	@echo "... yaml-cpp_autogen_timestamp_deps"
	@echo "... SDL2"
	@echo "... SDL2-static"
	@echo "... SDL2_image"
	@echo "... SDL2_mixer"
	@echo "... SDL2_test"
	@echo "... SDL2_ttf"
	@echo "... SDL2main"
	@echo "... SDL2pp"
	@echo "... taller_client"
	@echo "... taller_common"
	@echo "... taller_editor"
	@echo "... yaml-cpp"
	@echo "... yaml-cpp-parse"
	@echo "... yaml-cpp-read"
	@echo "... yaml-cpp-sandbox"
	@echo "... client/Pantallas/carselectscreen.o"
	@echo "... client/Pantallas/carselectscreen.i"
	@echo "... client/Pantallas/carselectscreen.s"
	@echo "... client/Pantallas/lobbyscreen.o"
	@echo "... client/Pantallas/lobbyscreen.i"
	@echo "... client/Pantallas/lobbyscreen.s"
	@echo "... client/Pantallas/loginscreen.o"
	@echo "... client/Pantallas/loginscreen.i"
	@echo "... client/Pantallas/loginscreen.s"
	@echo "... client/client.o"
	@echo "... client/client.i"
	@echo "... client/client.s"
	@echo "... client/client_main.o"
	@echo "... client/client_main.i"
	@echo "... client/client_main.s"
	@echo "... client/client_protocol.o"
	@echo "... client/client_protocol.i"
	@echo "... client/client_protocol.s"
	@echo "... client/client_receiver.o"
	@echo "... client/client_receiver.i"
	@echo "... client/client_receiver.s"
	@echo "... client/client_sender.o"
	@echo "... client/client_sender.i"
	@echo "... client/client_sender.s"
	@echo "... client/game_window.o"
	@echo "... client/game_window.i"
	@echo "... client/game_window.s"
	@echo "... client/mainwindow.o"
	@echo "... client/mainwindow.i"
	@echo "... client/mainwindow.s"
	@echo "... common/liberror.o"
	@echo "... common/liberror.i"
	@echo "... common/liberror.s"
	@echo "... common/resolver.o"
	@echo "... common/resolver.i"
	@echo "... common/resolver.s"
	@echo "... common/resolvererror.o"
	@echo "... common/resolvererror.i"
	@echo "... common/resolvererror.s"
	@echo "... common/socket.o"
	@echo "... common/socket.i"
	@echo "... common/socket.s"
	@echo "... editor/main.o"
	@echo "... editor/main.i"
	@echo "... editor/main.s"
	@echo "... editor/mainwindow.o"
	@echo "... editor/mainwindow.i"
	@echo "... editor/mainwindow.s"
	@echo "... taller_client_autogen/mocs_compilation.o"
	@echo "... taller_client_autogen/mocs_compilation.i"
	@echo "... taller_client_autogen/mocs_compilation.s"
	@echo "... taller_editor_autogen/mocs_compilation.o"
	@echo "... taller_editor_autogen/mocs_compilation.i"
	@echo "... taller_editor_autogen/mocs_compilation.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -P /home/nacho/Escritorio/TALLER/TP_final-2025c2-Grupo20/CMakeFiles/VerifyGlobs.cmake
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

