# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/nacho/Escritorio/TALLER/TP_final-2025c2-Grupo20

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/nacho/Escritorio/TALLER/TP_final-2025c2-Grupo20

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/nacho/Escritorio/TALLER/TP_final-2025c2-Grupo20/CMakeFiles /home/nacho/Escritorio/TALLER/TP_final-2025c2-Grupo20//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/nacho/Escritorio/TALLER/TP_final-2025c2-Grupo20/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -P /home/nacho/Escritorio/TALLER/TP_final-2025c2-Grupo20/CMakeFiles/VerifyGlobs.cmake
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named taller_common

# Build rule for target.
taller_common: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 taller_common
.PHONY : taller_common

# fast build rule for target.
taller_common/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_common.dir/build.make CMakeFiles/taller_common.dir/build
.PHONY : taller_common/fast

#=============================================================================
# Target rules for targets named taller_server

# Build rule for target.
taller_server: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 taller_server
.PHONY : taller_server

# fast build rule for target.
taller_server/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_server.dir/build.make CMakeFiles/taller_server.dir/build
.PHONY : taller_server/fast

#=============================================================================
# Target rules for targets named Experimental

# Build rule for target.
Experimental: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Experimental
.PHONY : Experimental

# fast build rule for target.
Experimental/fast:
	$(MAKE) $(MAKESILENT) -f _deps/yaml-cpp-build/CMakeFiles/Experimental.dir/build.make _deps/yaml-cpp-build/CMakeFiles/Experimental.dir/build
.PHONY : Experimental/fast

#=============================================================================
# Target rules for targets named Nightly

# Build rule for target.
Nightly: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Nightly
.PHONY : Nightly

# fast build rule for target.
Nightly/fast:
	$(MAKE) $(MAKESILENT) -f _deps/yaml-cpp-build/CMakeFiles/Nightly.dir/build.make _deps/yaml-cpp-build/CMakeFiles/Nightly.dir/build
.PHONY : Nightly/fast

#=============================================================================
# Target rules for targets named Continuous

# Build rule for target.
Continuous: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Continuous
.PHONY : Continuous

# fast build rule for target.
Continuous/fast:
	$(MAKE) $(MAKESILENT) -f _deps/yaml-cpp-build/CMakeFiles/Continuous.dir/build.make _deps/yaml-cpp-build/CMakeFiles/Continuous.dir/build
.PHONY : Continuous/fast

#=============================================================================
# Target rules for targets named NightlyMemoryCheck

# Build rule for target.
NightlyMemoryCheck: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyMemoryCheck
.PHONY : NightlyMemoryCheck

# fast build rule for target.
NightlyMemoryCheck/fast:
	$(MAKE) $(MAKESILENT) -f _deps/yaml-cpp-build/CMakeFiles/NightlyMemoryCheck.dir/build.make _deps/yaml-cpp-build/CMakeFiles/NightlyMemoryCheck.dir/build
.PHONY : NightlyMemoryCheck/fast

#=============================================================================
# Target rules for targets named NightlyStart

# Build rule for target.
NightlyStart: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyStart
.PHONY : NightlyStart

# fast build rule for target.
NightlyStart/fast:
	$(MAKE) $(MAKESILENT) -f _deps/yaml-cpp-build/CMakeFiles/NightlyStart.dir/build.make _deps/yaml-cpp-build/CMakeFiles/NightlyStart.dir/build
.PHONY : NightlyStart/fast

#=============================================================================
# Target rules for targets named NightlyUpdate

# Build rule for target.
NightlyUpdate: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyUpdate
.PHONY : NightlyUpdate

# fast build rule for target.
NightlyUpdate/fast:
	$(MAKE) $(MAKESILENT) -f _deps/yaml-cpp-build/CMakeFiles/NightlyUpdate.dir/build.make _deps/yaml-cpp-build/CMakeFiles/NightlyUpdate.dir/build
.PHONY : NightlyUpdate/fast

#=============================================================================
# Target rules for targets named NightlyConfigure

# Build rule for target.
NightlyConfigure: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyConfigure
.PHONY : NightlyConfigure

# fast build rule for target.
NightlyConfigure/fast:
	$(MAKE) $(MAKESILENT) -f _deps/yaml-cpp-build/CMakeFiles/NightlyConfigure.dir/build.make _deps/yaml-cpp-build/CMakeFiles/NightlyConfigure.dir/build
.PHONY : NightlyConfigure/fast

#=============================================================================
# Target rules for targets named NightlyBuild

# Build rule for target.
NightlyBuild: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyBuild
.PHONY : NightlyBuild

# fast build rule for target.
NightlyBuild/fast:
	$(MAKE) $(MAKESILENT) -f _deps/yaml-cpp-build/CMakeFiles/NightlyBuild.dir/build.make _deps/yaml-cpp-build/CMakeFiles/NightlyBuild.dir/build
.PHONY : NightlyBuild/fast

#=============================================================================
# Target rules for targets named NightlyTest

# Build rule for target.
NightlyTest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyTest
.PHONY : NightlyTest

# fast build rule for target.
NightlyTest/fast:
	$(MAKE) $(MAKESILENT) -f _deps/yaml-cpp-build/CMakeFiles/NightlyTest.dir/build.make _deps/yaml-cpp-build/CMakeFiles/NightlyTest.dir/build
.PHONY : NightlyTest/fast

#=============================================================================
# Target rules for targets named NightlyCoverage

# Build rule for target.
NightlyCoverage: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyCoverage
.PHONY : NightlyCoverage

# fast build rule for target.
NightlyCoverage/fast:
	$(MAKE) $(MAKESILENT) -f _deps/yaml-cpp-build/CMakeFiles/NightlyCoverage.dir/build.make _deps/yaml-cpp-build/CMakeFiles/NightlyCoverage.dir/build
.PHONY : NightlyCoverage/fast

#=============================================================================
# Target rules for targets named NightlyMemCheck

# Build rule for target.
NightlyMemCheck: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyMemCheck
.PHONY : NightlyMemCheck

# fast build rule for target.
NightlyMemCheck/fast:
	$(MAKE) $(MAKESILENT) -f _deps/yaml-cpp-build/CMakeFiles/NightlyMemCheck.dir/build.make _deps/yaml-cpp-build/CMakeFiles/NightlyMemCheck.dir/build
.PHONY : NightlyMemCheck/fast

#=============================================================================
# Target rules for targets named NightlySubmit

# Build rule for target.
NightlySubmit: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlySubmit
.PHONY : NightlySubmit

# fast build rule for target.
NightlySubmit/fast:
	$(MAKE) $(MAKESILENT) -f _deps/yaml-cpp-build/CMakeFiles/NightlySubmit.dir/build.make _deps/yaml-cpp-build/CMakeFiles/NightlySubmit.dir/build
.PHONY : NightlySubmit/fast

#=============================================================================
# Target rules for targets named ExperimentalStart

# Build rule for target.
ExperimentalStart: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalStart
.PHONY : ExperimentalStart

# fast build rule for target.
ExperimentalStart/fast:
	$(MAKE) $(MAKESILENT) -f _deps/yaml-cpp-build/CMakeFiles/ExperimentalStart.dir/build.make _deps/yaml-cpp-build/CMakeFiles/ExperimentalStart.dir/build
.PHONY : ExperimentalStart/fast

#=============================================================================
# Target rules for targets named ExperimentalUpdate

# Build rule for target.
ExperimentalUpdate: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalUpdate
.PHONY : ExperimentalUpdate

# fast build rule for target.
ExperimentalUpdate/fast:
	$(MAKE) $(MAKESILENT) -f _deps/yaml-cpp-build/CMakeFiles/ExperimentalUpdate.dir/build.make _deps/yaml-cpp-build/CMakeFiles/ExperimentalUpdate.dir/build
.PHONY : ExperimentalUpdate/fast

#=============================================================================
# Target rules for targets named ExperimentalConfigure

# Build rule for target.
ExperimentalConfigure: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalConfigure
.PHONY : ExperimentalConfigure

# fast build rule for target.
ExperimentalConfigure/fast:
	$(MAKE) $(MAKESILENT) -f _deps/yaml-cpp-build/CMakeFiles/ExperimentalConfigure.dir/build.make _deps/yaml-cpp-build/CMakeFiles/ExperimentalConfigure.dir/build
.PHONY : ExperimentalConfigure/fast

#=============================================================================
# Target rules for targets named ExperimentalBuild

# Build rule for target.
ExperimentalBuild: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalBuild
.PHONY : ExperimentalBuild

# fast build rule for target.
ExperimentalBuild/fast:
	$(MAKE) $(MAKESILENT) -f _deps/yaml-cpp-build/CMakeFiles/ExperimentalBuild.dir/build.make _deps/yaml-cpp-build/CMakeFiles/ExperimentalBuild.dir/build
.PHONY : ExperimentalBuild/fast

#=============================================================================
# Target rules for targets named ExperimentalTest

# Build rule for target.
ExperimentalTest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalTest
.PHONY : ExperimentalTest

# fast build rule for target.
ExperimentalTest/fast:
	$(MAKE) $(MAKESILENT) -f _deps/yaml-cpp-build/CMakeFiles/ExperimentalTest.dir/build.make _deps/yaml-cpp-build/CMakeFiles/ExperimentalTest.dir/build
.PHONY : ExperimentalTest/fast

#=============================================================================
# Target rules for targets named ExperimentalCoverage

# Build rule for target.
ExperimentalCoverage: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalCoverage
.PHONY : ExperimentalCoverage

# fast build rule for target.
ExperimentalCoverage/fast:
	$(MAKE) $(MAKESILENT) -f _deps/yaml-cpp-build/CMakeFiles/ExperimentalCoverage.dir/build.make _deps/yaml-cpp-build/CMakeFiles/ExperimentalCoverage.dir/build
.PHONY : ExperimentalCoverage/fast

#=============================================================================
# Target rules for targets named ExperimentalMemCheck

# Build rule for target.
ExperimentalMemCheck: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalMemCheck
.PHONY : ExperimentalMemCheck

# fast build rule for target.
ExperimentalMemCheck/fast:
	$(MAKE) $(MAKESILENT) -f _deps/yaml-cpp-build/CMakeFiles/ExperimentalMemCheck.dir/build.make _deps/yaml-cpp-build/CMakeFiles/ExperimentalMemCheck.dir/build
.PHONY : ExperimentalMemCheck/fast

#=============================================================================
# Target rules for targets named ExperimentalSubmit

# Build rule for target.
ExperimentalSubmit: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalSubmit
.PHONY : ExperimentalSubmit

# fast build rule for target.
ExperimentalSubmit/fast:
	$(MAKE) $(MAKESILENT) -f _deps/yaml-cpp-build/CMakeFiles/ExperimentalSubmit.dir/build.make _deps/yaml-cpp-build/CMakeFiles/ExperimentalSubmit.dir/build
.PHONY : ExperimentalSubmit/fast

#=============================================================================
# Target rules for targets named ContinuousStart

# Build rule for target.
ContinuousStart: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousStart
.PHONY : ContinuousStart

# fast build rule for target.
ContinuousStart/fast:
	$(MAKE) $(MAKESILENT) -f _deps/yaml-cpp-build/CMakeFiles/ContinuousStart.dir/build.make _deps/yaml-cpp-build/CMakeFiles/ContinuousStart.dir/build
.PHONY : ContinuousStart/fast

#=============================================================================
# Target rules for targets named ContinuousUpdate

# Build rule for target.
ContinuousUpdate: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousUpdate
.PHONY : ContinuousUpdate

# fast build rule for target.
ContinuousUpdate/fast:
	$(MAKE) $(MAKESILENT) -f _deps/yaml-cpp-build/CMakeFiles/ContinuousUpdate.dir/build.make _deps/yaml-cpp-build/CMakeFiles/ContinuousUpdate.dir/build
.PHONY : ContinuousUpdate/fast

#=============================================================================
# Target rules for targets named ContinuousConfigure

# Build rule for target.
ContinuousConfigure: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousConfigure
.PHONY : ContinuousConfigure

# fast build rule for target.
ContinuousConfigure/fast:
	$(MAKE) $(MAKESILENT) -f _deps/yaml-cpp-build/CMakeFiles/ContinuousConfigure.dir/build.make _deps/yaml-cpp-build/CMakeFiles/ContinuousConfigure.dir/build
.PHONY : ContinuousConfigure/fast

#=============================================================================
# Target rules for targets named ContinuousBuild

# Build rule for target.
ContinuousBuild: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousBuild
.PHONY : ContinuousBuild

# fast build rule for target.
ContinuousBuild/fast:
	$(MAKE) $(MAKESILENT) -f _deps/yaml-cpp-build/CMakeFiles/ContinuousBuild.dir/build.make _deps/yaml-cpp-build/CMakeFiles/ContinuousBuild.dir/build
.PHONY : ContinuousBuild/fast

#=============================================================================
# Target rules for targets named ContinuousTest

# Build rule for target.
ContinuousTest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousTest
.PHONY : ContinuousTest

# fast build rule for target.
ContinuousTest/fast:
	$(MAKE) $(MAKESILENT) -f _deps/yaml-cpp-build/CMakeFiles/ContinuousTest.dir/build.make _deps/yaml-cpp-build/CMakeFiles/ContinuousTest.dir/build
.PHONY : ContinuousTest/fast

#=============================================================================
# Target rules for targets named ContinuousCoverage

# Build rule for target.
ContinuousCoverage: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousCoverage
.PHONY : ContinuousCoverage

# fast build rule for target.
ContinuousCoverage/fast:
	$(MAKE) $(MAKESILENT) -f _deps/yaml-cpp-build/CMakeFiles/ContinuousCoverage.dir/build.make _deps/yaml-cpp-build/CMakeFiles/ContinuousCoverage.dir/build
.PHONY : ContinuousCoverage/fast

#=============================================================================
# Target rules for targets named ContinuousMemCheck

# Build rule for target.
ContinuousMemCheck: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousMemCheck
.PHONY : ContinuousMemCheck

# fast build rule for target.
ContinuousMemCheck/fast:
	$(MAKE) $(MAKESILENT) -f _deps/yaml-cpp-build/CMakeFiles/ContinuousMemCheck.dir/build.make _deps/yaml-cpp-build/CMakeFiles/ContinuousMemCheck.dir/build
.PHONY : ContinuousMemCheck/fast

#=============================================================================
# Target rules for targets named ContinuousSubmit

# Build rule for target.
ContinuousSubmit: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousSubmit
.PHONY : ContinuousSubmit

# fast build rule for target.
ContinuousSubmit/fast:
	$(MAKE) $(MAKESILENT) -f _deps/yaml-cpp-build/CMakeFiles/ContinuousSubmit.dir/build.make _deps/yaml-cpp-build/CMakeFiles/ContinuousSubmit.dir/build
.PHONY : ContinuousSubmit/fast

#=============================================================================
# Target rules for targets named yaml-cpp

# Build rule for target.
yaml-cpp: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 yaml-cpp
.PHONY : yaml-cpp

# fast build rule for target.
yaml-cpp/fast:
	$(MAKE) $(MAKESILENT) -f _deps/yaml-cpp-build/CMakeFiles/yaml-cpp.dir/build.make _deps/yaml-cpp-build/CMakeFiles/yaml-cpp.dir/build
.PHONY : yaml-cpp/fast

#=============================================================================
# Target rules for targets named format

# Build rule for target.
format: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 format
.PHONY : format

# fast build rule for target.
format/fast:
	$(MAKE) $(MAKESILENT) -f _deps/yaml-cpp-build/CMakeFiles/format.dir/build.make _deps/yaml-cpp-build/CMakeFiles/format.dir/build
.PHONY : format/fast

#=============================================================================
# Target rules for targets named yaml-cpp-sandbox

# Build rule for target.
yaml-cpp-sandbox: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 yaml-cpp-sandbox
.PHONY : yaml-cpp-sandbox

# fast build rule for target.
yaml-cpp-sandbox/fast:
	$(MAKE) $(MAKESILENT) -f _deps/yaml-cpp-build/util/CMakeFiles/yaml-cpp-sandbox.dir/build.make _deps/yaml-cpp-build/util/CMakeFiles/yaml-cpp-sandbox.dir/build
.PHONY : yaml-cpp-sandbox/fast

#=============================================================================
# Target rules for targets named yaml-cpp-parse

# Build rule for target.
yaml-cpp-parse: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 yaml-cpp-parse
.PHONY : yaml-cpp-parse

# fast build rule for target.
yaml-cpp-parse/fast:
	$(MAKE) $(MAKESILENT) -f _deps/yaml-cpp-build/util/CMakeFiles/yaml-cpp-parse.dir/build.make _deps/yaml-cpp-build/util/CMakeFiles/yaml-cpp-parse.dir/build
.PHONY : yaml-cpp-parse/fast

#=============================================================================
# Target rules for targets named yaml-cpp-read

# Build rule for target.
yaml-cpp-read: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 yaml-cpp-read
.PHONY : yaml-cpp-read

# fast build rule for target.
yaml-cpp-read/fast:
	$(MAKE) $(MAKESILENT) -f _deps/yaml-cpp-build/util/CMakeFiles/yaml-cpp-read.dir/build.make _deps/yaml-cpp-build/util/CMakeFiles/yaml-cpp-read.dir/build
.PHONY : yaml-cpp-read/fast

common/liberror.o: common/liberror.cpp.o
.PHONY : common/liberror.o

# target to build an object file
common/liberror.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_common.dir/build.make CMakeFiles/taller_common.dir/common/liberror.cpp.o
.PHONY : common/liberror.cpp.o

common/liberror.i: common/liberror.cpp.i
.PHONY : common/liberror.i

# target to preprocess a source file
common/liberror.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_common.dir/build.make CMakeFiles/taller_common.dir/common/liberror.cpp.i
.PHONY : common/liberror.cpp.i

common/liberror.s: common/liberror.cpp.s
.PHONY : common/liberror.s

# target to generate assembly for a file
common/liberror.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_common.dir/build.make CMakeFiles/taller_common.dir/common/liberror.cpp.s
.PHONY : common/liberror.cpp.s

common/resolver.o: common/resolver.cpp.o
.PHONY : common/resolver.o

# target to build an object file
common/resolver.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_common.dir/build.make CMakeFiles/taller_common.dir/common/resolver.cpp.o
.PHONY : common/resolver.cpp.o

common/resolver.i: common/resolver.cpp.i
.PHONY : common/resolver.i

# target to preprocess a source file
common/resolver.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_common.dir/build.make CMakeFiles/taller_common.dir/common/resolver.cpp.i
.PHONY : common/resolver.cpp.i

common/resolver.s: common/resolver.cpp.s
.PHONY : common/resolver.s

# target to generate assembly for a file
common/resolver.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_common.dir/build.make CMakeFiles/taller_common.dir/common/resolver.cpp.s
.PHONY : common/resolver.cpp.s

common/resolvererror.o: common/resolvererror.cpp.o
.PHONY : common/resolvererror.o

# target to build an object file
common/resolvererror.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_common.dir/build.make CMakeFiles/taller_common.dir/common/resolvererror.cpp.o
.PHONY : common/resolvererror.cpp.o

common/resolvererror.i: common/resolvererror.cpp.i
.PHONY : common/resolvererror.i

# target to preprocess a source file
common/resolvererror.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_common.dir/build.make CMakeFiles/taller_common.dir/common/resolvererror.cpp.i
.PHONY : common/resolvererror.cpp.i

common/resolvererror.s: common/resolvererror.cpp.s
.PHONY : common/resolvererror.s

# target to generate assembly for a file
common/resolvererror.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_common.dir/build.make CMakeFiles/taller_common.dir/common/resolvererror.cpp.s
.PHONY : common/resolvererror.cpp.s

common/socket.o: common/socket.cpp.o
.PHONY : common/socket.o

# target to build an object file
common/socket.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_common.dir/build.make CMakeFiles/taller_common.dir/common/socket.cpp.o
.PHONY : common/socket.cpp.o

common/socket.i: common/socket.cpp.i
.PHONY : common/socket.i

# target to preprocess a source file
common/socket.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_common.dir/build.make CMakeFiles/taller_common.dir/common/socket.cpp.i
.PHONY : common/socket.cpp.i

common/socket.s: common/socket.cpp.s
.PHONY : common/socket.s

# target to generate assembly for a file
common/socket.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_common.dir/build.make CMakeFiles/taller_common.dir/common/socket.cpp.s
.PHONY : common/socket.cpp.s

server/acceptor.o: server/acceptor.cpp.o
.PHONY : server/acceptor.o

# target to build an object file
server/acceptor.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_server.dir/build.make CMakeFiles/taller_server.dir/server/acceptor.cpp.o
.PHONY : server/acceptor.cpp.o

server/acceptor.i: server/acceptor.cpp.i
.PHONY : server/acceptor.i

# target to preprocess a source file
server/acceptor.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_server.dir/build.make CMakeFiles/taller_server.dir/server/acceptor.cpp.i
.PHONY : server/acceptor.cpp.i

server/acceptor.s: server/acceptor.cpp.s
.PHONY : server/acceptor.s

# target to generate assembly for a file
server/acceptor.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_server.dir/build.make CMakeFiles/taller_server.dir/server/acceptor.cpp.s
.PHONY : server/acceptor.cpp.s

server/client_handler.o: server/client_handler.cpp.o
.PHONY : server/client_handler.o

# target to build an object file
server/client_handler.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_server.dir/build.make CMakeFiles/taller_server.dir/server/client_handler.cpp.o
.PHONY : server/client_handler.cpp.o

server/client_handler.i: server/client_handler.cpp.i
.PHONY : server/client_handler.i

# target to preprocess a source file
server/client_handler.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_server.dir/build.make CMakeFiles/taller_server.dir/server/client_handler.cpp.i
.PHONY : server/client_handler.cpp.i

server/client_handler.s: server/client_handler.cpp.s
.PHONY : server/client_handler.s

# target to generate assembly for a file
server/client_handler.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_server.dir/build.make CMakeFiles/taller_server.dir/server/client_handler.cpp.s
.PHONY : server/client_handler.cpp.s

server/collisions_listener.o: server/collisions_listener.cpp.o
.PHONY : server/collisions_listener.o

# target to build an object file
server/collisions_listener.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_server.dir/build.make CMakeFiles/taller_server.dir/server/collisions_listener.cpp.o
.PHONY : server/collisions_listener.cpp.o

server/collisions_listener.i: server/collisions_listener.cpp.i
.PHONY : server/collisions_listener.i

# target to preprocess a source file
server/collisions_listener.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_server.dir/build.make CMakeFiles/taller_server.dir/server/collisions_listener.cpp.i
.PHONY : server/collisions_listener.cpp.i

server/collisions_listener.s: server/collisions_listener.cpp.s
.PHONY : server/collisions_listener.s

# target to generate assembly for a file
server/collisions_listener.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_server.dir/build.make CMakeFiles/taller_server.dir/server/collisions_listener.cpp.s
.PHONY : server/collisions_listener.cpp.s

server/gameloop.o: server/gameloop.cpp.o
.PHONY : server/gameloop.o

# target to build an object file
server/gameloop.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_server.dir/build.make CMakeFiles/taller_server.dir/server/gameloop.cpp.o
.PHONY : server/gameloop.cpp.o

server/gameloop.i: server/gameloop.cpp.i
.PHONY : server/gameloop.i

# target to preprocess a source file
server/gameloop.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_server.dir/build.make CMakeFiles/taller_server.dir/server/gameloop.cpp.i
.PHONY : server/gameloop.cpp.i

server/gameloop.s: server/gameloop.cpp.s
.PHONY : server/gameloop.s

# target to generate assembly for a file
server/gameloop.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_server.dir/build.make CMakeFiles/taller_server.dir/server/gameloop.cpp.s
.PHONY : server/gameloop.cpp.s

server/match.o: server/match.cpp.o
.PHONY : server/match.o

# target to build an object file
server/match.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_server.dir/build.make CMakeFiles/taller_server.dir/server/match.cpp.o
.PHONY : server/match.cpp.o

server/match.i: server/match.cpp.i
.PHONY : server/match.i

# target to preprocess a source file
server/match.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_server.dir/build.make CMakeFiles/taller_server.dir/server/match.cpp.i
.PHONY : server/match.cpp.i

server/match.s: server/match.cpp.s
.PHONY : server/match.s

# target to generate assembly for a file
server/match.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_server.dir/build.make CMakeFiles/taller_server.dir/server/match.cpp.s
.PHONY : server/match.cpp.s

server/queues_monitor.o: server/queues_monitor.cpp.o
.PHONY : server/queues_monitor.o

# target to build an object file
server/queues_monitor.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_server.dir/build.make CMakeFiles/taller_server.dir/server/queues_monitor.cpp.o
.PHONY : server/queues_monitor.cpp.o

server/queues_monitor.i: server/queues_monitor.cpp.i
.PHONY : server/queues_monitor.i

# target to preprocess a source file
server/queues_monitor.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_server.dir/build.make CMakeFiles/taller_server.dir/server/queues_monitor.cpp.i
.PHONY : server/queues_monitor.cpp.i

server/queues_monitor.s: server/queues_monitor.cpp.s
.PHONY : server/queues_monitor.s

# target to generate assembly for a file
server/queues_monitor.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_server.dir/build.make CMakeFiles/taller_server.dir/server/queues_monitor.cpp.s
.PHONY : server/queues_monitor.cpp.s

server/receiver.o: server/receiver.cpp.o
.PHONY : server/receiver.o

# target to build an object file
server/receiver.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_server.dir/build.make CMakeFiles/taller_server.dir/server/receiver.cpp.o
.PHONY : server/receiver.cpp.o

server/receiver.i: server/receiver.cpp.i
.PHONY : server/receiver.i

# target to preprocess a source file
server/receiver.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_server.dir/build.make CMakeFiles/taller_server.dir/server/receiver.cpp.i
.PHONY : server/receiver.cpp.i

server/receiver.s: server/receiver.cpp.s
.PHONY : server/receiver.s

# target to generate assembly for a file
server/receiver.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_server.dir/build.make CMakeFiles/taller_server.dir/server/receiver.cpp.s
.PHONY : server/receiver.cpp.s

server/sender.o: server/sender.cpp.o
.PHONY : server/sender.o

# target to build an object file
server/sender.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_server.dir/build.make CMakeFiles/taller_server.dir/server/sender.cpp.o
.PHONY : server/sender.cpp.o

server/sender.i: server/sender.cpp.i
.PHONY : server/sender.i

# target to preprocess a source file
server/sender.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_server.dir/build.make CMakeFiles/taller_server.dir/server/sender.cpp.i
.PHONY : server/sender.cpp.i

server/sender.s: server/sender.cpp.s
.PHONY : server/sender.s

# target to generate assembly for a file
server/sender.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_server.dir/build.make CMakeFiles/taller_server.dir/server/sender.cpp.s
.PHONY : server/sender.cpp.s

server/server.o: server/server.cpp.o
.PHONY : server/server.o

# target to build an object file
server/server.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_server.dir/build.make CMakeFiles/taller_server.dir/server/server.cpp.o
.PHONY : server/server.cpp.o

server/server.i: server/server.cpp.i
.PHONY : server/server.i

# target to preprocess a source file
server/server.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_server.dir/build.make CMakeFiles/taller_server.dir/server/server.cpp.i
.PHONY : server/server.cpp.i

server/server.s: server/server.cpp.s
.PHONY : server/server.s

# target to generate assembly for a file
server/server.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_server.dir/build.make CMakeFiles/taller_server.dir/server/server.cpp.s
.PHONY : server/server.cpp.s

server/server_main.o: server/server_main.cpp.o
.PHONY : server/server_main.o

# target to build an object file
server/server_main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_server.dir/build.make CMakeFiles/taller_server.dir/server/server_main.cpp.o
.PHONY : server/server_main.cpp.o

server/server_main.i: server/server_main.cpp.i
.PHONY : server/server_main.i

# target to preprocess a source file
server/server_main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_server.dir/build.make CMakeFiles/taller_server.dir/server/server_main.cpp.i
.PHONY : server/server_main.cpp.i

server/server_main.s: server/server_main.cpp.s
.PHONY : server/server_main.s

# target to generate assembly for a file
server/server_main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_server.dir/build.make CMakeFiles/taller_server.dir/server/server_main.cpp.s
.PHONY : server/server_main.cpp.s

server/server_protocol.o: server/server_protocol.cpp.o
.PHONY : server/server_protocol.o

# target to build an object file
server/server_protocol.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_server.dir/build.make CMakeFiles/taller_server.dir/server/server_protocol.cpp.o
.PHONY : server/server_protocol.cpp.o

server/server_protocol.i: server/server_protocol.cpp.i
.PHONY : server/server_protocol.i

# target to preprocess a source file
server/server_protocol.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_server.dir/build.make CMakeFiles/taller_server.dir/server/server_protocol.cpp.i
.PHONY : server/server_protocol.cpp.i

server/server_protocol.s: server/server_protocol.cpp.s
.PHONY : server/server_protocol.s

# target to generate assembly for a file
server/server_protocol.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_server.dir/build.make CMakeFiles/taller_server.dir/server/server_protocol.cpp.s
.PHONY : server/server_protocol.cpp.s

server/world_entities/car.o: server/world_entities/car.cpp.o
.PHONY : server/world_entities/car.o

# target to build an object file
server/world_entities/car.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_server.dir/build.make CMakeFiles/taller_server.dir/server/world_entities/car.cpp.o
.PHONY : server/world_entities/car.cpp.o

server/world_entities/car.i: server/world_entities/car.cpp.i
.PHONY : server/world_entities/car.i

# target to preprocess a source file
server/world_entities/car.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_server.dir/build.make CMakeFiles/taller_server.dir/server/world_entities/car.cpp.i
.PHONY : server/world_entities/car.cpp.i

server/world_entities/car.s: server/world_entities/car.cpp.s
.PHONY : server/world_entities/car.s

# target to generate assembly for a file
server/world_entities/car.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_server.dir/build.make CMakeFiles/taller_server.dir/server/world_entities/car.cpp.s
.PHONY : server/world_entities/car.cpp.s

server/world_entities/checkpoint.o: server/world_entities/checkpoint.cpp.o
.PHONY : server/world_entities/checkpoint.o

# target to build an object file
server/world_entities/checkpoint.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_server.dir/build.make CMakeFiles/taller_server.dir/server/world_entities/checkpoint.cpp.o
.PHONY : server/world_entities/checkpoint.cpp.o

server/world_entities/checkpoint.i: server/world_entities/checkpoint.cpp.i
.PHONY : server/world_entities/checkpoint.i

# target to preprocess a source file
server/world_entities/checkpoint.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_server.dir/build.make CMakeFiles/taller_server.dir/server/world_entities/checkpoint.cpp.i
.PHONY : server/world_entities/checkpoint.cpp.i

server/world_entities/checkpoint.s: server/world_entities/checkpoint.cpp.s
.PHONY : server/world_entities/checkpoint.s

# target to generate assembly for a file
server/world_entities/checkpoint.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_server.dir/build.make CMakeFiles/taller_server.dir/server/world_entities/checkpoint.cpp.s
.PHONY : server/world_entities/checkpoint.cpp.s

server/world_entities/wall.o: server/world_entities/wall.cpp.o
.PHONY : server/world_entities/wall.o

# target to build an object file
server/world_entities/wall.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_server.dir/build.make CMakeFiles/taller_server.dir/server/world_entities/wall.cpp.o
.PHONY : server/world_entities/wall.cpp.o

server/world_entities/wall.i: server/world_entities/wall.cpp.i
.PHONY : server/world_entities/wall.i

# target to preprocess a source file
server/world_entities/wall.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_server.dir/build.make CMakeFiles/taller_server.dir/server/world_entities/wall.cpp.i
.PHONY : server/world_entities/wall.cpp.i

server/world_entities/wall.s: server/world_entities/wall.cpp.s
.PHONY : server/world_entities/wall.s

# target to generate assembly for a file
server/world_entities/wall.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/taller_server.dir/build.make CMakeFiles/taller_server.dir/server/world_entities/wall.cpp.s
.PHONY : server/world_entities/wall.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... Continuous"
	@echo "... ContinuousBuild"
	@echo "... ContinuousConfigure"
	@echo "... ContinuousCoverage"
	@echo "... ContinuousMemCheck"
	@echo "... ContinuousStart"
	@echo "... ContinuousSubmit"
	@echo "... ContinuousTest"
	@echo "... ContinuousUpdate"
	@echo "... Experimental"
	@echo "... ExperimentalBuild"
	@echo "... ExperimentalConfigure"
	@echo "... ExperimentalCoverage"
	@echo "... ExperimentalMemCheck"
	@echo "... ExperimentalStart"
	@echo "... ExperimentalSubmit"
	@echo "... ExperimentalTest"
	@echo "... ExperimentalUpdate"
	@echo "... Nightly"
	@echo "... NightlyBuild"
	@echo "... NightlyConfigure"
	@echo "... NightlyCoverage"
	@echo "... NightlyMemCheck"
	@echo "... NightlyMemoryCheck"
	@echo "... NightlyStart"
	@echo "... NightlySubmit"
	@echo "... NightlyTest"
	@echo "... NightlyUpdate"
	@echo "... format"
	@echo "... taller_common"
	@echo "... taller_server"
	@echo "... yaml-cpp"
	@echo "... yaml-cpp-parse"
	@echo "... yaml-cpp-read"
	@echo "... yaml-cpp-sandbox"
	@echo "... common/liberror.o"
	@echo "... common/liberror.i"
	@echo "... common/liberror.s"
	@echo "... common/resolver.o"
	@echo "... common/resolver.i"
	@echo "... common/resolver.s"
	@echo "... common/resolvererror.o"
	@echo "... common/resolvererror.i"
	@echo "... common/resolvererror.s"
	@echo "... common/socket.o"
	@echo "... common/socket.i"
	@echo "... common/socket.s"
	@echo "... server/acceptor.o"
	@echo "... server/acceptor.i"
	@echo "... server/acceptor.s"
	@echo "... server/client_handler.o"
	@echo "... server/client_handler.i"
	@echo "... server/client_handler.s"
	@echo "... server/collisions_listener.o"
	@echo "... server/collisions_listener.i"
	@echo "... server/collisions_listener.s"
	@echo "... server/gameloop.o"
	@echo "... server/gameloop.i"
	@echo "... server/gameloop.s"
	@echo "... server/match.o"
	@echo "... server/match.i"
	@echo "... server/match.s"
	@echo "... server/queues_monitor.o"
	@echo "... server/queues_monitor.i"
	@echo "... server/queues_monitor.s"
	@echo "... server/receiver.o"
	@echo "... server/receiver.i"
	@echo "... server/receiver.s"
	@echo "... server/sender.o"
	@echo "... server/sender.i"
	@echo "... server/sender.s"
	@echo "... server/server.o"
	@echo "... server/server.i"
	@echo "... server/server.s"
	@echo "... server/server_main.o"
	@echo "... server/server_main.i"
	@echo "... server/server_main.s"
	@echo "... server/server_protocol.o"
	@echo "... server/server_protocol.i"
	@echo "... server/server_protocol.s"
	@echo "... server/world_entities/car.o"
	@echo "... server/world_entities/car.i"
	@echo "... server/world_entities/car.s"
	@echo "... server/world_entities/checkpoint.o"
	@echo "... server/world_entities/checkpoint.i"
	@echo "... server/world_entities/checkpoint.s"
	@echo "... server/world_entities/wall.o"
	@echo "... server/world_entities/wall.i"
	@echo "... server/world_entities/wall.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -P /home/nacho/Escritorio/TALLER/TP_final-2025c2-Grupo20/CMakeFiles/VerifyGlobs.cmake
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

